<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class WorldCurrenciesSeeder extends Seeder
{
    public function run(): void
    {
        Currency::withoutEvents(function (): void {
            foreach ($this->currencies() as $attributes) {
                $currency = Currency::query()
                    ->where('code', $attributes['code'])
                    ->orWhere('name', $attributes['name'])
                    ->first();

                $currency ??= new Currency();
                $currency->fill($attributes);
                $currency->save();
            }
        });
    }

    protected function currencies(): array
    {
        return [
            ['code' => 'AED', 'name' => 'UAE Dirham', 'sign' => 'د.إ', 'conversion_rate' => 1],
            ['code' => 'AFN', 'name' => 'Afghan Afghani', 'sign' => '؋', 'conversion_rate' => 1],
            ['code' => 'ALL', 'name' => 'Albanian Lek', 'sign' => 'L', 'conversion_rate' => 1],
            ['code' => 'AMD', 'name' => 'Armenian Dram', 'sign' => '֏', 'conversion_rate' => 1],
            ['code' => 'ANG', 'name' => 'Netherlands Antillean Guilder', 'sign' => 'ƒ', 'conversion_rate' => 1],
            ['code' => 'AOA', 'name' => 'Angolan Kwanza', 'sign' => 'Kz', 'conversion_rate' => 1],
            ['code' => 'ARS', 'name' => 'Argentine Peso', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'AUD', 'name' => 'Australian Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'AWG', 'name' => 'Aruban Florin', 'sign' => 'ƒ', 'conversion_rate' => 1],
            ['code' => 'AZN', 'name' => 'Azerbaijani Manat', 'sign' => '₼', 'conversion_rate' => 1],
            ['code' => 'BAM', 'name' => 'Bosnia-Herzegovina Convertible Mark', 'sign' => 'KM', 'conversion_rate' => 1],
            ['code' => 'BBD', 'name' => 'Barbadian Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'BDT', 'name' => 'Bangladeshi Taka', 'sign' => '৳', 'conversion_rate' => 1],
            ['code' => 'BGN', 'name' => 'Bulgarian Lev', 'sign' => 'лв', 'conversion_rate' => 1],
            ['code' => 'BHD', 'name' => 'Bahraini Dinar', 'sign' => '.د.ب', 'conversion_rate' => 1],
            ['code' => 'BIF', 'name' => 'Burundian Franc', 'sign' => 'FBu', 'conversion_rate' => 1],
            ['code' => 'BMD', 'name' => 'Bermudian Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'BND', 'name' => 'Brunei Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'BOB', 'name' => 'Bolivian Boliviano', 'sign' => 'Bs.', 'conversion_rate' => 1],
            ['code' => 'BRL', 'name' => 'Brazilian Real', 'sign' => 'R$', 'conversion_rate' => 1],
            ['code' => 'BSD', 'name' => 'Bahamian Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'BTN', 'name' => 'Bhutanese Ngultrum', 'sign' => 'Nu.', 'conversion_rate' => 1],
            ['code' => 'BWP', 'name' => 'Botswanan Pula', 'sign' => 'P', 'conversion_rate' => 1],
            ['code' => 'BYN', 'name' => 'Belarusian Ruble', 'sign' => 'Br', 'conversion_rate' => 1],
            ['code' => 'BZD', 'name' => 'Belize Dollar', 'sign' => 'BZ$', 'conversion_rate' => 1],
            ['code' => 'CAD', 'name' => 'Canadian Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'CDF', 'name' => 'Congolese Franc', 'sign' => 'FC', 'conversion_rate' => 1],
            ['code' => 'CHF', 'name' => 'Swiss Franc', 'sign' => 'CHF', 'conversion_rate' => 1],
            ['code' => 'CLP', 'name' => 'Chilean Peso', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'CNY', 'name' => 'Chinese Yuan', 'sign' => '¥', 'conversion_rate' => 1],
            ['code' => 'COP', 'name' => 'Colombian Peso', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'CRC', 'name' => 'Costa Rican Colon', 'sign' => '₡', 'conversion_rate' => 1],
            ['code' => 'CUP', 'name' => 'Cuban Peso', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'CVE', 'name' => 'Cape Verdean Escudo', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'CZK', 'name' => 'Czech Koruna', 'sign' => 'Kč', 'conversion_rate' => 1],
            ['code' => 'DJF', 'name' => 'Djiboutian Franc', 'sign' => 'Fdj', 'conversion_rate' => 1],
            ['code' => 'DKK', 'name' => 'Danish Krone', 'sign' => 'kr', 'conversion_rate' => 1],
            ['code' => 'DOP', 'name' => 'Dominican Peso', 'sign' => 'RD$', 'conversion_rate' => 1],
            ['code' => 'DZD', 'name' => 'Algerian Dinar', 'sign' => 'د.ج', 'conversion_rate' => 1],
            ['code' => 'EGP', 'name' => 'Egyptian Pound', 'sign' => '£', 'conversion_rate' => 1],
            ['code' => 'ERN', 'name' => 'Eritrean Nakfa', 'sign' => 'Nfk', 'conversion_rate' => 1],
            ['code' => 'ETB', 'name' => 'Ethiopian Birr', 'sign' => 'Br', 'conversion_rate' => 1],
            ['code' => 'EUR', 'name' => 'Euro', 'sign' => '€', 'conversion_rate' => 1],
            ['code' => 'FJD', 'name' => 'Fijian Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'FKP', 'name' => 'Falkland Islands Pound', 'sign' => '£', 'conversion_rate' => 1],
            ['code' => 'GBP', 'name' => 'British Pound Sterling', 'sign' => '£', 'conversion_rate' => 1],
            ['code' => 'GEL', 'name' => 'Georgian Lari', 'sign' => '₾', 'conversion_rate' => 1],
            ['code' => 'GHS', 'name' => 'Ghanaian Cedi', 'sign' => '₵', 'conversion_rate' => 1],
            ['code' => 'GIP', 'name' => 'Gibraltar Pound', 'sign' => '£', 'conversion_rate' => 1],
            ['code' => 'GMD', 'name' => 'Gambian Dalasi', 'sign' => 'D', 'conversion_rate' => 1],
            ['code' => 'GNF', 'name' => 'Guinean Franc', 'sign' => 'FG', 'conversion_rate' => 1],
            ['code' => 'GTQ', 'name' => 'Guatemalan Quetzal', 'sign' => 'Q', 'conversion_rate' => 1],
            ['code' => 'GYD', 'name' => 'Guyanaese Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'HKD', 'name' => 'Hong Kong Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'HNL', 'name' => 'Honduran Lempira', 'sign' => 'L', 'conversion_rate' => 1],
            ['code' => 'HTG', 'name' => 'Haitian Gourde', 'sign' => 'G', 'conversion_rate' => 1],
            ['code' => 'HUF', 'name' => 'Hungarian Forint', 'sign' => 'Ft', 'conversion_rate' => 1],
            ['code' => 'IDR', 'name' => 'Indonesian Rupiah', 'sign' => 'Rp', 'conversion_rate' => 1],
            ['code' => 'ILS', 'name' => 'Israeli New Shekel', 'sign' => '₪', 'conversion_rate' => 1],
            ['code' => 'INR', 'name' => 'Indian Rupee', 'sign' => '₹', 'conversion_rate' => 1],
            ['code' => 'IQD', 'name' => 'Iraqi Dinar', 'sign' => 'ع.د', 'conversion_rate' => 1],
            ['code' => 'IRR', 'name' => 'Iranian Rial', 'sign' => '﷼', 'conversion_rate' => 1],
            ['code' => 'ISK', 'name' => 'Icelandic Krona', 'sign' => 'kr', 'conversion_rate' => 1],
            ['code' => 'JMD', 'name' => 'Jamaican Dollar', 'sign' => 'J$', 'conversion_rate' => 1],
            ['code' => 'JOD', 'name' => 'Jordanian Dinar', 'sign' => 'د.ا', 'conversion_rate' => 1],
            ['code' => 'JPY', 'name' => 'Japanese Yen', 'sign' => '¥', 'conversion_rate' => 1],
            ['code' => 'KES', 'name' => 'Kenyan Shilling', 'sign' => 'KSh', 'conversion_rate' => 1],
            ['code' => 'KGS', 'name' => 'Kyrgystani Som', 'sign' => 'сом', 'conversion_rate' => 1],
            ['code' => 'KHR', 'name' => 'Cambodian Riel', 'sign' => '៛', 'conversion_rate' => 1],
            ['code' => 'KMF', 'name' => 'Comorian Franc', 'sign' => 'CF', 'conversion_rate' => 1],
            ['code' => 'KPW', 'name' => 'North Korean Won', 'sign' => '₩', 'conversion_rate' => 1],
            ['code' => 'KRW', 'name' => 'South Korean Won', 'sign' => '₩', 'conversion_rate' => 1],
            ['code' => 'KWD', 'name' => 'Kuwaiti Dinar', 'sign' => 'د.ك', 'conversion_rate' => 1],
            ['code' => 'KYD', 'name' => 'Cayman Islands Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'KZT', 'name' => 'Kazakhstani Tenge', 'sign' => '₸', 'conversion_rate' => 1],
            ['code' => 'LAK', 'name' => 'Lao Kip', 'sign' => '₭', 'conversion_rate' => 1],
            ['code' => 'LBP', 'name' => 'Lebanese Pound', 'sign' => 'ل.ل', 'conversion_rate' => 1],
            ['code' => 'LKR', 'name' => 'Sri Lankan Rupee', 'sign' => 'Rs', 'conversion_rate' => 1],
            ['code' => 'LRD', 'name' => 'Liberian Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'LSL', 'name' => 'Lesotho Loti', 'sign' => 'L', 'conversion_rate' => 1],
            ['code' => 'LYD', 'name' => 'Libyan Dinar', 'sign' => 'ل.د', 'conversion_rate' => 1],
            ['code' => 'MAD', 'name' => 'Moroccan Dirham', 'sign' => 'د.م.', 'conversion_rate' => 1],
            ['code' => 'MDL', 'name' => 'Moldovan Leu', 'sign' => 'L', 'conversion_rate' => 1],
            ['code' => 'MGA', 'name' => 'Malagasy Ariary', 'sign' => 'Ar', 'conversion_rate' => 1],
            ['code' => 'MKD', 'name' => 'Macedonian Denar', 'sign' => 'ден', 'conversion_rate' => 1],
            ['code' => 'MMK', 'name' => 'Myanmar Kyat', 'sign' => 'Ks', 'conversion_rate' => 1],
            ['code' => 'MNT', 'name' => 'Mongolian Tugrik', 'sign' => '₮', 'conversion_rate' => 1],
            ['code' => 'MOP', 'name' => 'Macanese Pataca', 'sign' => 'MOP$', 'conversion_rate' => 1],
            ['code' => 'MRU', 'name' => 'Mauritanian Ouguiya', 'sign' => 'UM', 'conversion_rate' => 1],
            ['code' => 'MUR', 'name' => 'Mauritian Rupee', 'sign' => '₨', 'conversion_rate' => 1],
            ['code' => 'MVR', 'name' => 'Maldivian Rufiyaa', 'sign' => 'Rf', 'conversion_rate' => 1],
            ['code' => 'MWK', 'name' => 'Malawian Kwacha', 'sign' => 'MK', 'conversion_rate' => 1],
            ['code' => 'MXN', 'name' => 'Mexican Peso', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'MYR', 'name' => 'Malaysian Ringgit', 'sign' => 'RM', 'conversion_rate' => 1],
            ['code' => 'MZN', 'name' => 'Mozambican Metical', 'sign' => 'MT', 'conversion_rate' => 1],
            ['code' => 'NAD', 'name' => 'Namibian Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'NGN', 'name' => 'Nigerian Naira', 'sign' => '₦', 'conversion_rate' => 1],
            ['code' => 'NIO', 'name' => 'Nicaraguan Cordoba', 'sign' => 'C$', 'conversion_rate' => 1],
            ['code' => 'NOK', 'name' => 'Norwegian Krone', 'sign' => 'kr', 'conversion_rate' => 1],
            ['code' => 'NPR', 'name' => 'Nepalese Rupee', 'sign' => '₨', 'conversion_rate' => 1],
            ['code' => 'NZD', 'name' => 'New Zealand Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'OMR', 'name' => 'Omani Rial', 'sign' => 'ر.ع.', 'conversion_rate' => 1],
            ['code' => 'PAB', 'name' => 'Panamanian Balboa', 'sign' => 'B/.', 'conversion_rate' => 1],
            ['code' => 'PEN', 'name' => 'Peruvian Sol', 'sign' => 'S/', 'conversion_rate' => 1],
            ['code' => 'PGK', 'name' => 'Papua New Guinean Kina', 'sign' => 'K', 'conversion_rate' => 1],
            ['code' => 'PHP', 'name' => 'Philippine Peso', 'sign' => '₱', 'conversion_rate' => 1],
            ['code' => 'PKR', 'name' => 'Pakistani Rupee', 'sign' => '₨', 'conversion_rate' => 1],
            ['code' => 'PLN', 'name' => 'Polish Zloty', 'sign' => 'zł', 'conversion_rate' => 1],
            ['code' => 'PYG', 'name' => 'Paraguayan Guarani', 'sign' => '₲', 'conversion_rate' => 1],
            ['code' => 'QAR', 'name' => 'Qatari Riyal', 'sign' => 'ر.ق', 'conversion_rate' => 1],
            ['code' => 'RON', 'name' => 'Romanian Leu', 'sign' => 'lei', 'conversion_rate' => 1],
            ['code' => 'RSD', 'name' => 'Serbian Dinar', 'sign' => 'дин.', 'conversion_rate' => 1],
            ['code' => 'RUB', 'name' => 'Russian Ruble', 'sign' => '₽', 'conversion_rate' => 1],
            ['code' => 'RWF', 'name' => 'Rwandan Franc', 'sign' => 'FRw', 'conversion_rate' => 1],
            ['code' => 'SAR', 'name' => 'Saudi Riyal', 'sign' => '﷼', 'conversion_rate' => 1],
            ['code' => 'SBD', 'name' => 'Solomon Islands Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'SCR', 'name' => 'Seychellois Rupee', 'sign' => '₨', 'conversion_rate' => 1],
            ['code' => 'SDG', 'name' => 'Sudanese Pound', 'sign' => 'ج.س.', 'conversion_rate' => 1],
            ['code' => 'SEK', 'name' => 'Swedish Krona', 'sign' => 'kr', 'conversion_rate' => 1],
            ['code' => 'SGD', 'name' => 'Singapore Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'SHP', 'name' => 'Saint Helena Pound', 'sign' => '£', 'conversion_rate' => 1],
            ['code' => 'SLE', 'name' => 'Sierra Leonean Leone', 'sign' => 'Le', 'conversion_rate' => 1],
            ['code' => 'SOS', 'name' => 'Somali Shilling', 'sign' => 'Sh', 'conversion_rate' => 1],
            ['code' => 'SRD', 'name' => 'Surinamese Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'SSP', 'name' => 'South Sudanese Pound', 'sign' => '£', 'conversion_rate' => 1],
            ['code' => 'STN', 'name' => 'Sao Tome and Principe Dobra', 'sign' => 'Db', 'conversion_rate' => 1],
            ['code' => 'SVC', 'name' => 'Salvadoran Colon', 'sign' => '₡', 'conversion_rate' => 1],
            ['code' => 'SYP', 'name' => 'Syrian Pound', 'sign' => '£', 'conversion_rate' => 1],
            ['code' => 'SZL', 'name' => 'Swazi Lilangeni', 'sign' => 'E', 'conversion_rate' => 1],
            ['code' => 'THB', 'name' => 'Thai Baht', 'sign' => '฿', 'conversion_rate' => 1],
            ['code' => 'TJS', 'name' => 'Tajikistani Somoni', 'sign' => 'ЅМ', 'conversion_rate' => 1],
            ['code' => 'TMT', 'name' => 'Turkmenistani Manat', 'sign' => 'm', 'conversion_rate' => 1],
            ['code' => 'TND', 'name' => 'Tunisian Dinar', 'sign' => 'د.ت', 'conversion_rate' => 1],
            ['code' => 'TOP', 'name' => 'Tongan Paanga', 'sign' => 'T$', 'conversion_rate' => 1],
            ['code' => 'TRY', 'name' => 'Turkish Lira', 'sign' => '₺', 'conversion_rate' => 1],
            ['code' => 'TTD', 'name' => 'Trinidad and Tobago Dollar', 'sign' => 'TT$', 'conversion_rate' => 1],
            ['code' => 'TWD', 'name' => 'New Taiwan Dollar', 'sign' => 'NT$', 'conversion_rate' => 1],
            ['code' => 'TZS', 'name' => 'Tanzanian Shilling', 'sign' => 'Sh', 'conversion_rate' => 1],
            ['code' => 'UAH', 'name' => 'Ukrainian Hryvnia', 'sign' => '₴', 'conversion_rate' => 1],
            ['code' => 'UGX', 'name' => 'Ugandan Shilling', 'sign' => 'USh', 'conversion_rate' => 1],
            ['code' => 'USD', 'name' => 'US Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'UYU', 'name' => 'Uruguayan Peso', 'sign' => '$U', 'conversion_rate' => 1],
            ['code' => 'UZS', 'name' => 'Uzbekistani Som', 'sign' => 'soʻm', 'conversion_rate' => 1],
            ['code' => 'VES', 'name' => 'Venezuelan Bolivar', 'sign' => 'Bs.', 'conversion_rate' => 1],
            ['code' => 'VND', 'name' => 'Vietnamese Dong', 'sign' => '₫', 'conversion_rate' => 1],
            ['code' => 'VUV', 'name' => 'Vanuatu Vatu', 'sign' => 'VT', 'conversion_rate' => 1],
            ['code' => 'WST', 'name' => 'Samoan Tala', 'sign' => 'WS$', 'conversion_rate' => 1],
            ['code' => 'XAF', 'name' => 'Central African CFA Franc', 'sign' => 'FCFA', 'conversion_rate' => 1],
            ['code' => 'XCD', 'name' => 'East Caribbean Dollar', 'sign' => '$', 'conversion_rate' => 1],
            ['code' => 'XOF', 'name' => 'West African CFA Franc', 'sign' => 'CFA', 'conversion_rate' => 1],
            ['code' => 'XPF', 'name' => 'CFP Franc', 'sign' => '₣', 'conversion_rate' => 1],
            ['code' => 'YER', 'name' => 'Yemeni Rial', 'sign' => '﷼', 'conversion_rate' => 1],
            ['code' => 'ZAR', 'name' => 'South African Rand', 'sign' => 'R', 'conversion_rate' => 1],
            ['code' => 'ZMW', 'name' => 'Zambian Kwacha', 'sign' => 'ZK', 'conversion_rate' => 1],
            ['code' => 'ZWL', 'name' => 'Zimbabwean Dollar', 'sign' => 'Z$', 'conversion_rate' => 1],
        ];
    }
}
