<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class WorldCountriesSeeder extends Seeder
{
    public function run(): void
    {
        $arabicNames = $this->arabicNames();

        Country::withoutEvents(function () use ($arabicNames): void {
            foreach ($this->countries() as $row) {
                $country = Country::query()->updateOrCreate(
                    ['iso2' => $row['iso2']],
                    $row,
                );

                if ($arabicName = $arabicNames[$row['iso2']] ?? null) {
                    $country->syncTranslations(['ar' => ['name' => $arabicName]]);
                }
            }
        });
    }

    /**
     * Each entry: iso2, iso3, name, currency_code, language_code, language_direction, phone_code, flag_emoji
     * language_direction: 'rtl' for Arabic, Hebrew, Persian, Urdu scripts; 'ltr' for all others.
     */
    protected function countries(): array
    {
        return [
            ['iso2' => 'AF', 'iso3' => 'AFG', 'name' => 'Afghanistan', 'currency_code' => 'AFN', 'language_code' => 'ps', 'language_direction' => 'rtl', 'phone_code' => '+93', 'flag_emoji' => '🇦🇫'],
            ['iso2' => 'AL', 'iso3' => 'ALB', 'name' => 'Albania', 'currency_code' => 'ALL', 'language_code' => 'sq', 'language_direction' => 'ltr', 'phone_code' => '+355', 'flag_emoji' => '🇦🇱'],
            ['iso2' => 'DZ', 'iso3' => 'DZA', 'name' => 'Algeria', 'currency_code' => 'DZD', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+213', 'flag_emoji' => '🇩🇿'],
            ['iso2' => 'AD', 'iso3' => 'AND', 'name' => 'Andorra', 'currency_code' => 'EUR', 'language_code' => 'ca', 'language_direction' => 'ltr', 'phone_code' => '+376', 'flag_emoji' => '🇦🇩'],
            ['iso2' => 'AO', 'iso3' => 'AGO', 'name' => 'Angola', 'currency_code' => 'AOA', 'language_code' => 'pt', 'language_direction' => 'ltr', 'phone_code' => '+244', 'flag_emoji' => '🇦🇴'],
            ['iso2' => 'AG', 'iso3' => 'ATG', 'name' => 'Antigua and Barbuda', 'currency_code' => 'XCD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+1-268', 'flag_emoji' => '🇦🇬'],
            ['iso2' => 'AR', 'iso3' => 'ARG', 'name' => 'Argentina', 'currency_code' => 'ARS', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+54', 'flag_emoji' => '🇦🇷'],
            ['iso2' => 'AM', 'iso3' => 'ARM', 'name' => 'Armenia', 'currency_code' => 'AMD', 'language_code' => 'hy', 'language_direction' => 'ltr', 'phone_code' => '+374', 'flag_emoji' => '🇦🇲'],
            ['iso2' => 'AU', 'iso3' => 'AUS', 'name' => 'Australia', 'currency_code' => 'AUD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+61', 'flag_emoji' => '🇦🇺'],
            ['iso2' => 'AT', 'iso3' => 'AUT', 'name' => 'Austria', 'currency_code' => 'EUR', 'language_code' => 'de', 'language_direction' => 'ltr', 'phone_code' => '+43', 'flag_emoji' => '🇦🇹'],
            ['iso2' => 'AZ', 'iso3' => 'AZE', 'name' => 'Azerbaijan', 'currency_code' => 'AZN', 'language_code' => 'az', 'language_direction' => 'ltr', 'phone_code' => '+994', 'flag_emoji' => '🇦🇿'],
            ['iso2' => 'BS', 'iso3' => 'BHS', 'name' => 'Bahamas', 'currency_code' => 'BSD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+1-242', 'flag_emoji' => '🇧🇸'],
            ['iso2' => 'BH', 'iso3' => 'BHR', 'name' => 'Bahrain', 'currency_code' => 'BHD', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+973', 'flag_emoji' => '🇧🇭'],
            ['iso2' => 'BD', 'iso3' => 'BGD', 'name' => 'Bangladesh', 'currency_code' => 'BDT', 'language_code' => 'bn', 'language_direction' => 'ltr', 'phone_code' => '+880', 'flag_emoji' => '🇧🇩'],
            ['iso2' => 'BB', 'iso3' => 'BRB', 'name' => 'Barbados', 'currency_code' => 'BBD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+1-246', 'flag_emoji' => '🇧🇧'],
            ['iso2' => 'BY', 'iso3' => 'BLR', 'name' => 'Belarus', 'currency_code' => 'BYN', 'language_code' => 'be', 'language_direction' => 'ltr', 'phone_code' => '+375', 'flag_emoji' => '🇧🇾'],
            ['iso2' => 'BE', 'iso3' => 'BEL', 'name' => 'Belgium', 'currency_code' => 'EUR', 'language_code' => 'nl', 'language_direction' => 'ltr', 'phone_code' => '+32', 'flag_emoji' => '🇧🇪'],
            ['iso2' => 'BZ', 'iso3' => 'BLZ', 'name' => 'Belize', 'currency_code' => 'BZD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+501', 'flag_emoji' => '🇧🇿'],
            ['iso2' => 'BJ', 'iso3' => 'BEN', 'name' => 'Benin', 'currency_code' => 'XOF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+229', 'flag_emoji' => '🇧🇯'],
            ['iso2' => 'BT', 'iso3' => 'BTN', 'name' => 'Bhutan', 'currency_code' => 'BTN', 'language_code' => 'dz', 'language_direction' => 'ltr', 'phone_code' => '+975', 'flag_emoji' => '🇧🇹'],
            ['iso2' => 'BO', 'iso3' => 'BOL', 'name' => 'Bolivia', 'currency_code' => 'BOB', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+591', 'flag_emoji' => '🇧🇴'],
            ['iso2' => 'BA', 'iso3' => 'BIH', 'name' => 'Bosnia and Herzegovina', 'currency_code' => 'BAM', 'language_code' => 'bs', 'language_direction' => 'ltr', 'phone_code' => '+387', 'flag_emoji' => '🇧🇦'],
            ['iso2' => 'BW', 'iso3' => 'BWA', 'name' => 'Botswana', 'currency_code' => 'BWP', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+267', 'flag_emoji' => '🇧🇼'],
            ['iso2' => 'BR', 'iso3' => 'BRA', 'name' => 'Brazil', 'currency_code' => 'BRL', 'language_code' => 'pt', 'language_direction' => 'ltr', 'phone_code' => '+55', 'flag_emoji' => '🇧🇷'],
            ['iso2' => 'BN', 'iso3' => 'BRN', 'name' => 'Brunei', 'currency_code' => 'BND', 'language_code' => 'ms', 'language_direction' => 'ltr', 'phone_code' => '+673', 'flag_emoji' => '🇧🇳'],
            ['iso2' => 'BG', 'iso3' => 'BGR', 'name' => 'Bulgaria', 'currency_code' => 'BGN', 'language_code' => 'bg', 'language_direction' => 'ltr', 'phone_code' => '+359', 'flag_emoji' => '🇧🇬'],
            ['iso2' => 'BF', 'iso3' => 'BFA', 'name' => 'Burkina Faso', 'currency_code' => 'XOF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+226', 'flag_emoji' => '🇧🇫'],
            ['iso2' => 'BI', 'iso3' => 'BDI', 'name' => 'Burundi', 'currency_code' => 'BIF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+257', 'flag_emoji' => '🇧🇮'],
            ['iso2' => 'CV', 'iso3' => 'CPV', 'name' => 'Cabo Verde', 'currency_code' => 'CVE', 'language_code' => 'pt', 'language_direction' => 'ltr', 'phone_code' => '+238', 'flag_emoji' => '🇨🇻'],
            ['iso2' => 'KH', 'iso3' => 'KHM', 'name' => 'Cambodia', 'currency_code' => 'KHR', 'language_code' => 'km', 'language_direction' => 'ltr', 'phone_code' => '+855', 'flag_emoji' => '🇰🇭'],
            ['iso2' => 'CM', 'iso3' => 'CMR', 'name' => 'Cameroon', 'currency_code' => 'XAF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+237', 'flag_emoji' => '🇨🇲'],
            ['iso2' => 'CA', 'iso3' => 'CAN', 'name' => 'Canada', 'currency_code' => 'CAD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+1', 'flag_emoji' => '🇨🇦'],
            ['iso2' => 'CF', 'iso3' => 'CAF', 'name' => 'Central African Republic', 'currency_code' => 'XAF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+236', 'flag_emoji' => '🇨🇫'],
            ['iso2' => 'TD', 'iso3' => 'TCD', 'name' => 'Chad', 'currency_code' => 'XAF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+235', 'flag_emoji' => '🇹🇩'],
            ['iso2' => 'CL', 'iso3' => 'CHL', 'name' => 'Chile', 'currency_code' => 'CLP', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+56', 'flag_emoji' => '🇨🇱'],
            ['iso2' => 'CN', 'iso3' => 'CHN', 'name' => 'China', 'currency_code' => 'CNY', 'language_code' => 'zh', 'language_direction' => 'ltr', 'phone_code' => '+86', 'flag_emoji' => '🇨🇳'],
            ['iso2' => 'CO', 'iso3' => 'COL', 'name' => 'Colombia', 'currency_code' => 'COP', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+57', 'flag_emoji' => '🇨🇴'],
            ['iso2' => 'KM', 'iso3' => 'COM', 'name' => 'Comoros', 'currency_code' => 'KMF', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+269', 'flag_emoji' => '🇰🇲'],
            ['iso2' => 'CD', 'iso3' => 'COD', 'name' => 'Congo (DRC)', 'currency_code' => 'CDF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+243', 'flag_emoji' => '🇨🇩'],
            ['iso2' => 'CG', 'iso3' => 'COG', 'name' => 'Congo (Republic)', 'currency_code' => 'XAF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+242', 'flag_emoji' => '🇨🇬'],
            ['iso2' => 'CR', 'iso3' => 'CRI', 'name' => 'Costa Rica', 'currency_code' => 'CRC', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+506', 'flag_emoji' => '🇨🇷'],
            ['iso2' => 'HR', 'iso3' => 'HRV', 'name' => 'Croatia', 'currency_code' => 'EUR', 'language_code' => 'hr', 'language_direction' => 'ltr', 'phone_code' => '+385', 'flag_emoji' => '🇭🇷'],
            ['iso2' => 'CU', 'iso3' => 'CUB', 'name' => 'Cuba', 'currency_code' => 'CUP', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+53', 'flag_emoji' => '🇨🇺'],
            ['iso2' => 'CY', 'iso3' => 'CYP', 'name' => 'Cyprus', 'currency_code' => 'EUR', 'language_code' => 'el', 'language_direction' => 'ltr', 'phone_code' => '+357', 'flag_emoji' => '🇨🇾'],
            ['iso2' => 'CZ', 'iso3' => 'CZE', 'name' => 'Czech Republic', 'currency_code' => 'CZK', 'language_code' => 'cs', 'language_direction' => 'ltr', 'phone_code' => '+420', 'flag_emoji' => '🇨🇿'],
            ['iso2' => 'CI', 'iso3' => 'CIV', 'name' => 'Côte d\'Ivoire', 'currency_code' => 'XOF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+225', 'flag_emoji' => '🇨🇮'],
            ['iso2' => 'DK', 'iso3' => 'DNK', 'name' => 'Denmark', 'currency_code' => 'DKK', 'language_code' => 'da', 'language_direction' => 'ltr', 'phone_code' => '+45', 'flag_emoji' => '🇩🇰'],
            ['iso2' => 'DJ', 'iso3' => 'DJI', 'name' => 'Djibouti', 'currency_code' => 'DJF', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+253', 'flag_emoji' => '🇩🇯'],
            ['iso2' => 'DM', 'iso3' => 'DMA', 'name' => 'Dominica', 'currency_code' => 'XCD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+1-767', 'flag_emoji' => '🇩🇲'],
            ['iso2' => 'DO', 'iso3' => 'DOM', 'name' => 'Dominican Republic', 'currency_code' => 'DOP', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+1-809', 'flag_emoji' => '🇩🇴'],
            ['iso2' => 'EC', 'iso3' => 'ECU', 'name' => 'Ecuador', 'currency_code' => 'USD', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+593', 'flag_emoji' => '🇪🇨'],
            ['iso2' => 'EG', 'iso3' => 'EGY', 'name' => 'Egypt', 'currency_code' => 'EGP', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+20', 'flag_emoji' => '🇪🇬'],
            ['iso2' => 'SV', 'iso3' => 'SLV', 'name' => 'El Salvador', 'currency_code' => 'USD', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+503', 'flag_emoji' => '🇸🇻'],
            ['iso2' => 'GQ', 'iso3' => 'GNQ', 'name' => 'Equatorial Guinea', 'currency_code' => 'XAF', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+240', 'flag_emoji' => '🇬🇶'],
            ['iso2' => 'ER', 'iso3' => 'ERI', 'name' => 'Eritrea', 'currency_code' => 'ERN', 'language_code' => 'ti', 'language_direction' => 'ltr', 'phone_code' => '+291', 'flag_emoji' => '🇪🇷'],
            ['iso2' => 'EE', 'iso3' => 'EST', 'name' => 'Estonia', 'currency_code' => 'EUR', 'language_code' => 'et', 'language_direction' => 'ltr', 'phone_code' => '+372', 'flag_emoji' => '🇪🇪'],
            ['iso2' => 'SZ', 'iso3' => 'SWZ', 'name' => 'Eswatini', 'currency_code' => 'SZL', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+268', 'flag_emoji' => '🇸🇿'],
            ['iso2' => 'ET', 'iso3' => 'ETH', 'name' => 'Ethiopia', 'currency_code' => 'ETB', 'language_code' => 'am', 'language_direction' => 'ltr', 'phone_code' => '+251', 'flag_emoji' => '🇪🇹'],
            ['iso2' => 'FJ', 'iso3' => 'FJI', 'name' => 'Fiji', 'currency_code' => 'FJD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+679', 'flag_emoji' => '🇫🇯'],
            ['iso2' => 'FI', 'iso3' => 'FIN', 'name' => 'Finland', 'currency_code' => 'EUR', 'language_code' => 'fi', 'language_direction' => 'ltr', 'phone_code' => '+358', 'flag_emoji' => '🇫🇮'],
            ['iso2' => 'FR', 'iso3' => 'FRA', 'name' => 'France', 'currency_code' => 'EUR', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+33', 'flag_emoji' => '🇫🇷'],
            ['iso2' => 'GA', 'iso3' => 'GAB', 'name' => 'Gabon', 'currency_code' => 'XAF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+241', 'flag_emoji' => '🇬🇦'],
            ['iso2' => 'GM', 'iso3' => 'GMB', 'name' => 'Gambia', 'currency_code' => 'GMD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+220', 'flag_emoji' => '🇬🇲'],
            ['iso2' => 'GE', 'iso3' => 'GEO', 'name' => 'Georgia', 'currency_code' => 'GEL', 'language_code' => 'ka', 'language_direction' => 'ltr', 'phone_code' => '+995', 'flag_emoji' => '🇬🇪'],
            ['iso2' => 'DE', 'iso3' => 'DEU', 'name' => 'Germany', 'currency_code' => 'EUR', 'language_code' => 'de', 'language_direction' => 'ltr', 'phone_code' => '+49', 'flag_emoji' => '🇩🇪'],
            ['iso2' => 'GH', 'iso3' => 'GHA', 'name' => 'Ghana', 'currency_code' => 'GHS', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+233', 'flag_emoji' => '🇬🇭'],
            ['iso2' => 'GR', 'iso3' => 'GRC', 'name' => 'Greece', 'currency_code' => 'EUR', 'language_code' => 'el', 'language_direction' => 'ltr', 'phone_code' => '+30', 'flag_emoji' => '🇬🇷'],
            ['iso2' => 'GD', 'iso3' => 'GRD', 'name' => 'Grenada', 'currency_code' => 'XCD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+1-473', 'flag_emoji' => '🇬🇩'],
            ['iso2' => 'GT', 'iso3' => 'GTM', 'name' => 'Guatemala', 'currency_code' => 'GTQ', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+502', 'flag_emoji' => '🇬🇹'],
            ['iso2' => 'GN', 'iso3' => 'GIN', 'name' => 'Guinea', 'currency_code' => 'GNF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+224', 'flag_emoji' => '🇬🇳'],
            ['iso2' => 'GW', 'iso3' => 'GNB', 'name' => 'Guinea-Bissau', 'currency_code' => 'XOF', 'language_code' => 'pt', 'language_direction' => 'ltr', 'phone_code' => '+245', 'flag_emoji' => '🇬🇼'],
            ['iso2' => 'GY', 'iso3' => 'GUY', 'name' => 'Guyana', 'currency_code' => 'GYD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+592', 'flag_emoji' => '🇬🇾'],
            ['iso2' => 'HT', 'iso3' => 'HTI', 'name' => 'Haiti', 'currency_code' => 'HTG', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+509', 'flag_emoji' => '🇭🇹'],
            ['iso2' => 'HN', 'iso3' => 'HND', 'name' => 'Honduras', 'currency_code' => 'HNL', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+504', 'flag_emoji' => '🇭🇳'],
            ['iso2' => 'HU', 'iso3' => 'HUN', 'name' => 'Hungary', 'currency_code' => 'HUF', 'language_code' => 'hu', 'language_direction' => 'ltr', 'phone_code' => '+36', 'flag_emoji' => '🇭🇺'],
            ['iso2' => 'IS', 'iso3' => 'ISL', 'name' => 'Iceland', 'currency_code' => 'ISK', 'language_code' => 'is', 'language_direction' => 'ltr', 'phone_code' => '+354', 'flag_emoji' => '🇮🇸'],
            ['iso2' => 'IN', 'iso3' => 'IND', 'name' => 'India', 'currency_code' => 'INR', 'language_code' => 'hi', 'language_direction' => 'ltr', 'phone_code' => '+91', 'flag_emoji' => '🇮🇳'],
            ['iso2' => 'ID', 'iso3' => 'IDN', 'name' => 'Indonesia', 'currency_code' => 'IDR', 'language_code' => 'id', 'language_direction' => 'ltr', 'phone_code' => '+62', 'flag_emoji' => '🇮🇩'],
            ['iso2' => 'IR', 'iso3' => 'IRN', 'name' => 'Iran', 'currency_code' => 'IRR', 'language_code' => 'fa', 'language_direction' => 'rtl', 'phone_code' => '+98', 'flag_emoji' => '🇮🇷'],
            ['iso2' => 'IQ', 'iso3' => 'IRQ', 'name' => 'Iraq', 'currency_code' => 'IQD', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+964', 'flag_emoji' => '🇮🇶'],
            ['iso2' => 'IE', 'iso3' => 'IRL', 'name' => 'Ireland', 'currency_code' => 'EUR', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+353', 'flag_emoji' => '🇮🇪'],
            ['iso2' => 'IL', 'iso3' => 'ISR', 'name' => 'Israel', 'currency_code' => 'ILS', 'language_code' => 'he', 'language_direction' => 'rtl', 'phone_code' => '+972', 'flag_emoji' => '🇮🇱'],
            ['iso2' => 'IT', 'iso3' => 'ITA', 'name' => 'Italy', 'currency_code' => 'EUR', 'language_code' => 'it', 'language_direction' => 'ltr', 'phone_code' => '+39', 'flag_emoji' => '🇮🇹'],
            ['iso2' => 'JM', 'iso3' => 'JAM', 'name' => 'Jamaica', 'currency_code' => 'JMD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+1-876', 'flag_emoji' => '🇯🇲'],
            ['iso2' => 'JP', 'iso3' => 'JPN', 'name' => 'Japan', 'currency_code' => 'JPY', 'language_code' => 'ja', 'language_direction' => 'ltr', 'phone_code' => '+81', 'flag_emoji' => '🇯🇵'],
            ['iso2' => 'JO', 'iso3' => 'JOR', 'name' => 'Jordan', 'currency_code' => 'JOD', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+962', 'flag_emoji' => '🇯🇴'],
            ['iso2' => 'KZ', 'iso3' => 'KAZ', 'name' => 'Kazakhstan', 'currency_code' => 'KZT', 'language_code' => 'kk', 'language_direction' => 'ltr', 'phone_code' => '+7', 'flag_emoji' => '🇰🇿'],
            ['iso2' => 'KE', 'iso3' => 'KEN', 'name' => 'Kenya', 'currency_code' => 'KES', 'language_code' => 'sw', 'language_direction' => 'ltr', 'phone_code' => '+254', 'flag_emoji' => '🇰🇪'],
            ['iso2' => 'KI', 'iso3' => 'KIR', 'name' => 'Kiribati', 'currency_code' => 'AUD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+686', 'flag_emoji' => '🇰🇮'],
            ['iso2' => 'KW', 'iso3' => 'KWT', 'name' => 'Kuwait', 'currency_code' => 'KWD', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+965', 'flag_emoji' => '🇰🇼'],
            ['iso2' => 'KG', 'iso3' => 'KGZ', 'name' => 'Kyrgyzstan', 'currency_code' => 'KGS', 'language_code' => 'ky', 'language_direction' => 'ltr', 'phone_code' => '+996', 'flag_emoji' => '🇰🇬'],
            ['iso2' => 'LA', 'iso3' => 'LAO', 'name' => 'Laos', 'currency_code' => 'LAK', 'language_code' => 'lo', 'language_direction' => 'ltr', 'phone_code' => '+856', 'flag_emoji' => '🇱🇦'],
            ['iso2' => 'LV', 'iso3' => 'LVA', 'name' => 'Latvia', 'currency_code' => 'EUR', 'language_code' => 'lv', 'language_direction' => 'ltr', 'phone_code' => '+371', 'flag_emoji' => '🇱🇻'],
            ['iso2' => 'LB', 'iso3' => 'LBN', 'name' => 'Lebanon', 'currency_code' => 'LBP', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+961', 'flag_emoji' => '🇱🇧'],
            ['iso2' => 'LS', 'iso3' => 'LSO', 'name' => 'Lesotho', 'currency_code' => 'LSL', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+266', 'flag_emoji' => '🇱🇸'],
            ['iso2' => 'LR', 'iso3' => 'LBR', 'name' => 'Liberia', 'currency_code' => 'LRD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+231', 'flag_emoji' => '🇱🇷'],
            ['iso2' => 'LY', 'iso3' => 'LBY', 'name' => 'Libya', 'currency_code' => 'LYD', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+218', 'flag_emoji' => '🇱🇾'],
            ['iso2' => 'LI', 'iso3' => 'LIE', 'name' => 'Liechtenstein', 'currency_code' => 'CHF', 'language_code' => 'de', 'language_direction' => 'ltr', 'phone_code' => '+423', 'flag_emoji' => '🇱🇮'],
            ['iso2' => 'LT', 'iso3' => 'LTU', 'name' => 'Lithuania', 'currency_code' => 'EUR', 'language_code' => 'lt', 'language_direction' => 'ltr', 'phone_code' => '+370', 'flag_emoji' => '🇱🇹'],
            ['iso2' => 'LU', 'iso3' => 'LUX', 'name' => 'Luxembourg', 'currency_code' => 'EUR', 'language_code' => 'lb', 'language_direction' => 'ltr', 'phone_code' => '+352', 'flag_emoji' => '🇱🇺'],
            ['iso2' => 'MG', 'iso3' => 'MDG', 'name' => 'Madagascar', 'currency_code' => 'MGA', 'language_code' => 'mg', 'language_direction' => 'ltr', 'phone_code' => '+261', 'flag_emoji' => '🇲🇬'],
            ['iso2' => 'MW', 'iso3' => 'MWI', 'name' => 'Malawi', 'currency_code' => 'MWK', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+265', 'flag_emoji' => '🇲🇼'],
            ['iso2' => 'MY', 'iso3' => 'MYS', 'name' => 'Malaysia', 'currency_code' => 'MYR', 'language_code' => 'ms', 'language_direction' => 'ltr', 'phone_code' => '+60', 'flag_emoji' => '🇲🇾'],
            ['iso2' => 'MV', 'iso3' => 'MDV', 'name' => 'Maldives', 'currency_code' => 'MVR', 'language_code' => 'dv', 'language_direction' => 'rtl', 'phone_code' => '+960', 'flag_emoji' => '🇲🇻'],
            ['iso2' => 'ML', 'iso3' => 'MLI', 'name' => 'Mali', 'currency_code' => 'XOF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+223', 'flag_emoji' => '🇲🇱'],
            ['iso2' => 'MT', 'iso3' => 'MLT', 'name' => 'Malta', 'currency_code' => 'EUR', 'language_code' => 'mt', 'language_direction' => 'ltr', 'phone_code' => '+356', 'flag_emoji' => '🇲🇹'],
            ['iso2' => 'MH', 'iso3' => 'MHL', 'name' => 'Marshall Islands', 'currency_code' => 'USD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+692', 'flag_emoji' => '🇲🇭'],
            ['iso2' => 'MR', 'iso3' => 'MRT', 'name' => 'Mauritania', 'currency_code' => 'MRU', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+222', 'flag_emoji' => '🇲🇷'],
            ['iso2' => 'MU', 'iso3' => 'MUS', 'name' => 'Mauritius', 'currency_code' => 'MUR', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+230', 'flag_emoji' => '🇲🇺'],
            ['iso2' => 'MX', 'iso3' => 'MEX', 'name' => 'Mexico', 'currency_code' => 'MXN', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+52', 'flag_emoji' => '🇲🇽'],
            ['iso2' => 'FM', 'iso3' => 'FSM', 'name' => 'Micronesia', 'currency_code' => 'USD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+691', 'flag_emoji' => '🇫🇲'],
            ['iso2' => 'MD', 'iso3' => 'MDA', 'name' => 'Moldova', 'currency_code' => 'MDL', 'language_code' => 'ro', 'language_direction' => 'ltr', 'phone_code' => '+373', 'flag_emoji' => '🇲🇩'],
            ['iso2' => 'MC', 'iso3' => 'MCO', 'name' => 'Monaco', 'currency_code' => 'EUR', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+377', 'flag_emoji' => '🇲🇨'],
            ['iso2' => 'MN', 'iso3' => 'MNG', 'name' => 'Mongolia', 'currency_code' => 'MNT', 'language_code' => 'mn', 'language_direction' => 'ltr', 'phone_code' => '+976', 'flag_emoji' => '🇲🇳'],
            ['iso2' => 'ME', 'iso3' => 'MNE', 'name' => 'Montenegro', 'currency_code' => 'EUR', 'language_code' => 'sr', 'language_direction' => 'ltr', 'phone_code' => '+382', 'flag_emoji' => '🇲🇪'],
            ['iso2' => 'MA', 'iso3' => 'MAR', 'name' => 'Morocco', 'currency_code' => 'MAD', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+212', 'flag_emoji' => '🇲🇦'],
            ['iso2' => 'MZ', 'iso3' => 'MOZ', 'name' => 'Mozambique', 'currency_code' => 'MZN', 'language_code' => 'pt', 'language_direction' => 'ltr', 'phone_code' => '+258', 'flag_emoji' => '🇲🇿'],
            ['iso2' => 'MM', 'iso3' => 'MMR', 'name' => 'Myanmar', 'currency_code' => 'MMK', 'language_code' => 'my', 'language_direction' => 'ltr', 'phone_code' => '+95', 'flag_emoji' => '🇲🇲'],
            ['iso2' => 'NA', 'iso3' => 'NAM', 'name' => 'Namibia', 'currency_code' => 'NAD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+264', 'flag_emoji' => '🇳🇦'],
            ['iso2' => 'NR', 'iso3' => 'NRU', 'name' => 'Nauru', 'currency_code' => 'AUD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+674', 'flag_emoji' => '🇳🇷'],
            ['iso2' => 'NP', 'iso3' => 'NPL', 'name' => 'Nepal', 'currency_code' => 'NPR', 'language_code' => 'ne', 'language_direction' => 'ltr', 'phone_code' => '+977', 'flag_emoji' => '🇳🇵'],
            ['iso2' => 'NL', 'iso3' => 'NLD', 'name' => 'Netherlands', 'currency_code' => 'EUR', 'language_code' => 'nl', 'language_direction' => 'ltr', 'phone_code' => '+31', 'flag_emoji' => '🇳🇱'],
            ['iso2' => 'NZ', 'iso3' => 'NZL', 'name' => 'New Zealand', 'currency_code' => 'NZD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+64', 'flag_emoji' => '🇳🇿'],
            ['iso2' => 'NI', 'iso3' => 'NIC', 'name' => 'Nicaragua', 'currency_code' => 'NIO', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+505', 'flag_emoji' => '🇳🇮'],
            ['iso2' => 'NE', 'iso3' => 'NER', 'name' => 'Niger', 'currency_code' => 'XOF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+227', 'flag_emoji' => '🇳🇪'],
            ['iso2' => 'NG', 'iso3' => 'NGA', 'name' => 'Nigeria', 'currency_code' => 'NGN', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+234', 'flag_emoji' => '🇳🇬'],
            ['iso2' => 'KP', 'iso3' => 'PRK', 'name' => 'North Korea', 'currency_code' => 'KPW', 'language_code' => 'ko', 'language_direction' => 'ltr', 'phone_code' => '+850', 'flag_emoji' => '🇰🇵'],
            ['iso2' => 'MK', 'iso3' => 'MKD', 'name' => 'North Macedonia', 'currency_code' => 'MKD', 'language_code' => 'mk', 'language_direction' => 'ltr', 'phone_code' => '+389', 'flag_emoji' => '🇲🇰'],
            ['iso2' => 'NO', 'iso3' => 'NOR', 'name' => 'Norway', 'currency_code' => 'NOK', 'language_code' => 'no', 'language_direction' => 'ltr', 'phone_code' => '+47', 'flag_emoji' => '🇳🇴'],
            ['iso2' => 'OM', 'iso3' => 'OMN', 'name' => 'Oman', 'currency_code' => 'OMR', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+968', 'flag_emoji' => '🇴🇲'],
            ['iso2' => 'PK', 'iso3' => 'PAK', 'name' => 'Pakistan', 'currency_code' => 'PKR', 'language_code' => 'ur', 'language_direction' => 'rtl', 'phone_code' => '+92', 'flag_emoji' => '🇵🇰'],
            ['iso2' => 'PW', 'iso3' => 'PLW', 'name' => 'Palau', 'currency_code' => 'USD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+680', 'flag_emoji' => '🇵🇼'],
            ['iso2' => 'PA', 'iso3' => 'PAN', 'name' => 'Panama', 'currency_code' => 'PAB', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+507', 'flag_emoji' => '🇵🇦'],
            ['iso2' => 'PG', 'iso3' => 'PNG', 'name' => 'Papua New Guinea', 'currency_code' => 'PGK', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+675', 'flag_emoji' => '🇵🇬'],
            ['iso2' => 'PY', 'iso3' => 'PRY', 'name' => 'Paraguay', 'currency_code' => 'PYG', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+595', 'flag_emoji' => '🇵🇾'],
            ['iso2' => 'PE', 'iso3' => 'PER', 'name' => 'Peru', 'currency_code' => 'PEN', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+51', 'flag_emoji' => '🇵🇪'],
            ['iso2' => 'PH', 'iso3' => 'PHL', 'name' => 'Philippines', 'currency_code' => 'PHP', 'language_code' => 'tl', 'language_direction' => 'ltr', 'phone_code' => '+63', 'flag_emoji' => '🇵🇭'],
            ['iso2' => 'PL', 'iso3' => 'POL', 'name' => 'Poland', 'currency_code' => 'PLN', 'language_code' => 'pl', 'language_direction' => 'ltr', 'phone_code' => '+48', 'flag_emoji' => '🇵🇱'],
            ['iso2' => 'PT', 'iso3' => 'PRT', 'name' => 'Portugal', 'currency_code' => 'EUR', 'language_code' => 'pt', 'language_direction' => 'ltr', 'phone_code' => '+351', 'flag_emoji' => '🇵🇹'],
            ['iso2' => 'QA', 'iso3' => 'QAT', 'name' => 'Qatar', 'currency_code' => 'QAR', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+974', 'flag_emoji' => '🇶🇦'],
            ['iso2' => 'RO', 'iso3' => 'ROU', 'name' => 'Romania', 'currency_code' => 'RON', 'language_code' => 'ro', 'language_direction' => 'ltr', 'phone_code' => '+40', 'flag_emoji' => '🇷🇴'],
            ['iso2' => 'RU', 'iso3' => 'RUS', 'name' => 'Russia', 'currency_code' => 'RUB', 'language_code' => 'ru', 'language_direction' => 'ltr', 'phone_code' => '+7', 'flag_emoji' => '🇷🇺'],
            ['iso2' => 'RW', 'iso3' => 'RWA', 'name' => 'Rwanda', 'currency_code' => 'RWF', 'language_code' => 'rw', 'language_direction' => 'ltr', 'phone_code' => '+250', 'flag_emoji' => '🇷🇼'],
            ['iso2' => 'KN', 'iso3' => 'KNA', 'name' => 'Saint Kitts and Nevis', 'currency_code' => 'XCD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+1-869', 'flag_emoji' => '🇰🇳'],
            ['iso2' => 'LC', 'iso3' => 'LCA', 'name' => 'Saint Lucia', 'currency_code' => 'XCD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+1-758', 'flag_emoji' => '🇱🇨'],
            ['iso2' => 'VC', 'iso3' => 'VCT', 'name' => 'Saint Vincent and the Grenadines', 'currency_code' => 'XCD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+1-784', 'flag_emoji' => '🇻🇨'],
            ['iso2' => 'WS', 'iso3' => 'WSM', 'name' => 'Samoa', 'currency_code' => 'WST', 'language_code' => 'sm', 'language_direction' => 'ltr', 'phone_code' => '+685', 'flag_emoji' => '🇼🇸'],
            ['iso2' => 'SM', 'iso3' => 'SMR', 'name' => 'San Marino', 'currency_code' => 'EUR', 'language_code' => 'it', 'language_direction' => 'ltr', 'phone_code' => '+378', 'flag_emoji' => '🇸🇲'],
            ['iso2' => 'ST', 'iso3' => 'STP', 'name' => 'Sao Tome and Principe', 'currency_code' => 'STN', 'language_code' => 'pt', 'language_direction' => 'ltr', 'phone_code' => '+239', 'flag_emoji' => '🇸🇹'],
            ['iso2' => 'SA', 'iso3' => 'SAU', 'name' => 'Saudi Arabia', 'currency_code' => 'SAR', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+966', 'flag_emoji' => '🇸🇦'],
            ['iso2' => 'SN', 'iso3' => 'SEN', 'name' => 'Senegal', 'currency_code' => 'XOF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+221', 'flag_emoji' => '🇸🇳'],
            ['iso2' => 'RS', 'iso3' => 'SRB', 'name' => 'Serbia', 'currency_code' => 'RSD', 'language_code' => 'sr', 'language_direction' => 'ltr', 'phone_code' => '+381', 'flag_emoji' => '🇷🇸'],
            ['iso2' => 'SC', 'iso3' => 'SYC', 'name' => 'Seychelles', 'currency_code' => 'SCR', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+248', 'flag_emoji' => '🇸🇨'],
            ['iso2' => 'SL', 'iso3' => 'SLE', 'name' => 'Sierra Leone', 'currency_code' => 'SLE', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+232', 'flag_emoji' => '🇸🇱'],
            ['iso2' => 'SG', 'iso3' => 'SGP', 'name' => 'Singapore', 'currency_code' => 'SGD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+65', 'flag_emoji' => '🇸🇬'],
            ['iso2' => 'SK', 'iso3' => 'SVK', 'name' => 'Slovakia', 'currency_code' => 'EUR', 'language_code' => 'sk', 'language_direction' => 'ltr', 'phone_code' => '+421', 'flag_emoji' => '🇸🇰'],
            ['iso2' => 'SI', 'iso3' => 'SVN', 'name' => 'Slovenia', 'currency_code' => 'EUR', 'language_code' => 'sl', 'language_direction' => 'ltr', 'phone_code' => '+386', 'flag_emoji' => '🇸🇮'],
            ['iso2' => 'SB', 'iso3' => 'SLB', 'name' => 'Solomon Islands', 'currency_code' => 'SBD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+677', 'flag_emoji' => '🇸🇧'],
            ['iso2' => 'SO', 'iso3' => 'SOM', 'name' => 'Somalia', 'currency_code' => 'SOS', 'language_code' => 'so', 'language_direction' => 'ltr', 'phone_code' => '+252', 'flag_emoji' => '🇸🇴'],
            ['iso2' => 'ZA', 'iso3' => 'ZAF', 'name' => 'South Africa', 'currency_code' => 'ZAR', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+27', 'flag_emoji' => '🇿🇦'],
            ['iso2' => 'SS', 'iso3' => 'SSD', 'name' => 'South Sudan', 'currency_code' => 'SSP', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+211', 'flag_emoji' => '🇸🇸'],
            ['iso2' => 'ES', 'iso3' => 'ESP', 'name' => 'Spain', 'currency_code' => 'EUR', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+34', 'flag_emoji' => '🇪🇸'],
            ['iso2' => 'LK', 'iso3' => 'LKA', 'name' => 'Sri Lanka', 'currency_code' => 'LKR', 'language_code' => 'si', 'language_direction' => 'ltr', 'phone_code' => '+94', 'flag_emoji' => '🇱🇰'],
            ['iso2' => 'SD', 'iso3' => 'SDN', 'name' => 'Sudan', 'currency_code' => 'SDG', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+249', 'flag_emoji' => '🇸🇩'],
            ['iso2' => 'SR', 'iso3' => 'SUR', 'name' => 'Suriname', 'currency_code' => 'SRD', 'language_code' => 'nl', 'language_direction' => 'ltr', 'phone_code' => '+597', 'flag_emoji' => '🇸🇷'],
            ['iso2' => 'SE', 'iso3' => 'SWE', 'name' => 'Sweden', 'currency_code' => 'SEK', 'language_code' => 'sv', 'language_direction' => 'ltr', 'phone_code' => '+46', 'flag_emoji' => '🇸🇪'],
            ['iso2' => 'CH', 'iso3' => 'CHE', 'name' => 'Switzerland', 'currency_code' => 'CHF', 'language_code' => 'de', 'language_direction' => 'ltr', 'phone_code' => '+41', 'flag_emoji' => '🇨🇭'],
            ['iso2' => 'SY', 'iso3' => 'SYR', 'name' => 'Syria', 'currency_code' => 'SYP', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+963', 'flag_emoji' => '🇸🇾'],
            ['iso2' => 'TW', 'iso3' => 'TWN', 'name' => 'Taiwan', 'currency_code' => 'TWD', 'language_code' => 'zh', 'language_direction' => 'ltr', 'phone_code' => '+886', 'flag_emoji' => '🇹🇼'],
            ['iso2' => 'TJ', 'iso3' => 'TJK', 'name' => 'Tajikistan', 'currency_code' => 'TJS', 'language_code' => 'tg', 'language_direction' => 'ltr', 'phone_code' => '+992', 'flag_emoji' => '🇹🇯'],
            ['iso2' => 'TZ', 'iso3' => 'TZA', 'name' => 'Tanzania', 'currency_code' => 'TZS', 'language_code' => 'sw', 'language_direction' => 'ltr', 'phone_code' => '+255', 'flag_emoji' => '🇹🇿'],
            ['iso2' => 'TH', 'iso3' => 'THA', 'name' => 'Thailand', 'currency_code' => 'THB', 'language_code' => 'th', 'language_direction' => 'ltr', 'phone_code' => '+66', 'flag_emoji' => '🇹🇭'],
            ['iso2' => 'TL', 'iso3' => 'TLS', 'name' => 'Timor-Leste', 'currency_code' => 'USD', 'language_code' => 'pt', 'language_direction' => 'ltr', 'phone_code' => '+670', 'flag_emoji' => '🇹🇱'],
            ['iso2' => 'TG', 'iso3' => 'TGO', 'name' => 'Togo', 'currency_code' => 'XOF', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+228', 'flag_emoji' => '🇹🇬'],
            ['iso2' => 'TO', 'iso3' => 'TON', 'name' => 'Tonga', 'currency_code' => 'TOP', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+676', 'flag_emoji' => '🇹🇴'],
            ['iso2' => 'TT', 'iso3' => 'TTO', 'name' => 'Trinidad and Tobago', 'currency_code' => 'TTD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+1-868', 'flag_emoji' => '🇹🇹'],
            ['iso2' => 'TN', 'iso3' => 'TUN', 'name' => 'Tunisia', 'currency_code' => 'TND', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+216', 'flag_emoji' => '🇹🇳'],
            ['iso2' => 'TR', 'iso3' => 'TUR', 'name' => 'Turkey', 'currency_code' => 'TRY', 'language_code' => 'tr', 'language_direction' => 'ltr', 'phone_code' => '+90', 'flag_emoji' => '🇹🇷'],
            ['iso2' => 'TM', 'iso3' => 'TKM', 'name' => 'Turkmenistan', 'currency_code' => 'TMT', 'language_code' => 'tk', 'language_direction' => 'ltr', 'phone_code' => '+993', 'flag_emoji' => '🇹🇲'],
            ['iso2' => 'TV', 'iso3' => 'TUV', 'name' => 'Tuvalu', 'currency_code' => 'AUD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+688', 'flag_emoji' => '🇹🇻'],
            ['iso2' => 'UG', 'iso3' => 'UGA', 'name' => 'Uganda', 'currency_code' => 'UGX', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+256', 'flag_emoji' => '🇺🇬'],
            ['iso2' => 'UA', 'iso3' => 'UKR', 'name' => 'Ukraine', 'currency_code' => 'UAH', 'language_code' => 'uk', 'language_direction' => 'ltr', 'phone_code' => '+380', 'flag_emoji' => '🇺🇦'],
            ['iso2' => 'AE', 'iso3' => 'ARE', 'name' => 'United Arab Emirates', 'currency_code' => 'AED', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+971', 'flag_emoji' => '🇦🇪'],
            ['iso2' => 'GB', 'iso3' => 'GBR', 'name' => 'United Kingdom', 'currency_code' => 'GBP', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+44', 'flag_emoji' => '🇬🇧'],
            ['iso2' => 'US', 'iso3' => 'USA', 'name' => 'United States', 'currency_code' => 'USD', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+1', 'flag_emoji' => '🇺🇸'],
            ['iso2' => 'UY', 'iso3' => 'URY', 'name' => 'Uruguay', 'currency_code' => 'UYU', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+598', 'flag_emoji' => '🇺🇾'],
            ['iso2' => 'UZ', 'iso3' => 'UZB', 'name' => 'Uzbekistan', 'currency_code' => 'UZS', 'language_code' => 'uz', 'language_direction' => 'ltr', 'phone_code' => '+998', 'flag_emoji' => '🇺🇿'],
            ['iso2' => 'VU', 'iso3' => 'VUT', 'name' => 'Vanuatu', 'currency_code' => 'VUV', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+678', 'flag_emoji' => '🇻🇺'],
            ['iso2' => 'VE', 'iso3' => 'VEN', 'name' => 'Venezuela', 'currency_code' => 'VES', 'language_code' => 'es', 'language_direction' => 'ltr', 'phone_code' => '+58', 'flag_emoji' => '🇻🇪'],
            ['iso2' => 'VN', 'iso3' => 'VNM', 'name' => 'Vietnam', 'currency_code' => 'VND', 'language_code' => 'vi', 'language_direction' => 'ltr', 'phone_code' => '+84', 'flag_emoji' => '🇻🇳'],
            ['iso2' => 'YE', 'iso3' => 'YEM', 'name' => 'Yemen', 'currency_code' => 'YER', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+967', 'flag_emoji' => '🇾🇪'],
            ['iso2' => 'ZM', 'iso3' => 'ZMB', 'name' => 'Zambia', 'currency_code' => 'ZMW', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+260', 'flag_emoji' => '🇿🇲'],
            ['iso2' => 'ZW', 'iso3' => 'ZWE', 'name' => 'Zimbabwe', 'currency_code' => 'ZWL', 'language_code' => 'en', 'language_direction' => 'ltr', 'phone_code' => '+263', 'flag_emoji' => '🇿🇼'],
            ['iso2' => 'KR', 'iso3' => 'KOR', 'name' => 'South Korea', 'currency_code' => 'KRW', 'language_code' => 'ko', 'language_direction' => 'ltr', 'phone_code' => '+82', 'flag_emoji' => '🇰🇷'],
            ['iso2' => 'PS', 'iso3' => 'PSE', 'name' => 'Palestine', 'currency_code' => 'ILS', 'language_code' => 'ar', 'language_direction' => 'rtl', 'phone_code' => '+970', 'flag_emoji' => '🇵🇸'],
            ['iso2' => 'TF', 'iso3' => 'ATF', 'name' => 'French Southern Territories', 'currency_code' => 'EUR', 'language_code' => 'fr', 'language_direction' => 'ltr', 'phone_code' => '+262', 'flag_emoji' => '🇹🇫'],
            ['iso2' => 'VA', 'iso3' => 'VAT', 'name' => 'Vatican City', 'currency_code' => 'EUR', 'language_code' => 'it', 'language_direction' => 'ltr', 'phone_code' => '+39-06', 'flag_emoji' => '🇻🇦'],
            ['iso2' => 'XK', 'iso3' => 'XKX', 'name' => 'Kosovo', 'currency_code' => 'EUR', 'language_code' => 'sq', 'language_direction' => 'ltr', 'phone_code' => '+383', 'flag_emoji' => '🇽🇰'],
        ];
    }

    /**
     * Arabic display names for each country, keyed by iso2.
     */
    protected function arabicNames(): array
    {
        return [
            'AF' => 'أفغانستان', 'AL' => 'ألبانيا', 'DZ' => 'الجزائر', 'AD' => 'أندورا', 'AO' => 'أنغولا',
            'AG' => 'أنتيغوا وباربودا', 'AR' => 'الأرجنتين', 'AM' => 'أرمينيا', 'AU' => 'أستراليا', 'AT' => 'النمسا',
            'AZ' => 'أذربيجان', 'BS' => 'باهاماس', 'BH' => 'البحرين', 'BD' => 'بنغلاديش', 'BB' => 'باربادوس',
            'BY' => 'بيلاروسيا', 'BE' => 'بلجيكا', 'BZ' => 'بليز', 'BJ' => 'بنين', 'BT' => 'بوتان',
            'BO' => 'بوليفيا', 'BA' => 'البوسنة والهرسك', 'BW' => 'بوتسوانا', 'BR' => 'البرازيل', 'BN' => 'بروناي',
            'BG' => 'بلغاريا', 'BF' => 'بوركينا فاسو', 'BI' => 'بوروندي', 'CV' => 'الرأس الأخضر', 'KH' => 'كمبوديا',
            'CM' => 'الكاميرون', 'CA' => 'كندا', 'CF' => 'جمهورية أفريقيا الوسطى', 'TD' => 'تشاد', 'CL' => 'تشيلي',
            'CN' => 'الصين', 'CO' => 'كولومبيا', 'KM' => 'جزر القمر', 'CD' => 'الكونغو الديمقراطية', 'CG' => 'الكونغو',
            'CR' => 'كوستاريكا', 'HR' => 'كرواتيا', 'CU' => 'كوبا', 'CY' => 'قبرص', 'CZ' => 'التشيك',
            'CI' => 'ساحل العاج', 'DK' => 'الدنمارك', 'DJ' => 'جيبوتي', 'DM' => 'دومينيكا', 'DO' => 'جمهورية الدومينيكان',
            'EC' => 'الإكوادور', 'EG' => 'مصر', 'SV' => 'السلفادور', 'GQ' => 'غينيا الاستوائية', 'ER' => 'إريتريا',
            'EE' => 'إستونيا', 'SZ' => 'إسواتيني', 'ET' => 'إثيوبيا', 'FJ' => 'فيجي', 'FI' => 'فنلندا',
            'FR' => 'فرنسا', 'GA' => 'الغابون', 'GM' => 'غامبيا', 'GE' => 'جورجيا', 'DE' => 'ألمانيا',
            'GH' => 'غانا', 'GR' => 'اليونان', 'GD' => 'غرينادا', 'GT' => 'غواتيمالا', 'GN' => 'غينيا',
            'GW' => 'غينيا بيساو', 'GY' => 'غيانا', 'HT' => 'هايتي', 'HN' => 'هندوراس', 'HU' => 'المجر',
            'IS' => 'آيسلندا', 'IN' => 'الهند', 'ID' => 'إندونيسيا', 'IR' => 'إيران', 'IQ' => 'العراق',
            'IE' => 'أيرلندا', 'IL' => 'إسرائيل', 'IT' => 'إيطاليا', 'JM' => 'جامايكا', 'JP' => 'اليابان',
            'JO' => 'الأردن', 'KZ' => 'كازاخستان', 'KE' => 'كينيا', 'KI' => 'كيريباتي', 'KW' => 'الكويت',
            'KG' => 'قيرغيزستان', 'LA' => 'لاوس', 'LV' => 'لاتفيا', 'LB' => 'لبنان', 'LS' => 'ليسوتو',
            'LR' => 'ليبيريا', 'LY' => 'ليبيا', 'LI' => 'ليختنشتاين', 'LT' => 'ليتوانيا', 'LU' => 'لوكسمبورغ',
            'MG' => 'مدغشقر', 'MW' => 'مالاوي', 'MY' => 'ماليزيا', 'MV' => 'المالديف', 'ML' => 'مالي',
            'MT' => 'مالطا', 'MH' => 'جزر مارشال', 'MR' => 'موريتانيا', 'MU' => 'موريشيوس', 'MX' => 'المكسيك',
            'FM' => 'ميكرونيزيا', 'MD' => 'مولدوفا', 'MC' => 'موناكو', 'MN' => 'منغوليا', 'ME' => 'الجبل الأسود',
            'MA' => 'المغرب', 'MZ' => 'موزمبيق', 'MM' => 'ميانمار', 'NA' => 'ناميبيا', 'NR' => 'ناورو',
            'NP' => 'نيبال', 'NL' => 'هولندا', 'NZ' => 'نيوزيلندا', 'NI' => 'نيكاراغوا', 'NE' => 'النيجر',
            'NG' => 'نيجيريا', 'KP' => 'كوريا الشمالية', 'MK' => 'مقدونيا الشمالية', 'NO' => 'النرويج', 'OM' => 'عُمان',
            'PK' => 'باكستان', 'PW' => 'بالاو', 'PA' => 'بنما', 'PG' => 'بابوا غينيا الجديدة', 'PY' => 'باراغواي',
            'PE' => 'بيرو', 'PH' => 'الفلبين', 'PL' => 'بولندا', 'PT' => 'البرتغال', 'QA' => 'قطر',
            'RO' => 'رومانيا', 'RU' => 'روسيا', 'RW' => 'رواندا', 'KN' => 'سانت كيتس ونيفيس', 'LC' => 'سانت لوسيا',
            'VC' => 'سانت فينسنت والغرينادين', 'WS' => 'ساموا', 'SM' => 'سان مارينو', 'ST' => 'ساو تومي وبرينسيبي', 'SA' => 'المملكة العربية السعودية',
            'SN' => 'السنغال', 'RS' => 'صربيا', 'SC' => 'سيشل', 'SL' => 'سيراليون', 'SG' => 'سنغافورة',
            'SK' => 'سلوفاكيا', 'SI' => 'سلوفينيا', 'SB' => 'جزر سليمان', 'SO' => 'الصومال', 'ZA' => 'جنوب أفريقيا',
            'SS' => 'جنوب السودان', 'ES' => 'إسبانيا', 'LK' => 'سريلانكا', 'SD' => 'السودان', 'SR' => 'سورينام',
            'SE' => 'السويد', 'CH' => 'سويسرا', 'SY' => 'سوريا', 'TW' => 'تايوان', 'TJ' => 'طاجيكستان',
            'TZ' => 'تنزانيا', 'TH' => 'تايلاند', 'TL' => 'تيمور الشرقية', 'TG' => 'توغو', 'TO' => 'تونغا',
            'TT' => 'ترينيداد وتوباغو', 'TN' => 'تونس', 'TR' => 'تركيا', 'TM' => 'تركمانستان', 'TV' => 'توفالو',
            'UG' => 'أوغندا', 'UA' => 'أوكرانيا', 'AE' => 'الإمارات العربية المتحدة', 'GB' => 'المملكة المتحدة', 'US' => 'الولايات المتحدة',
            'UY' => 'الأوروغواي', 'UZ' => 'أوزبكستان', 'VU' => 'فانواتو', 'VE' => 'فنزويلا', 'VN' => 'فيتنام',
            'YE' => 'اليمن', 'ZM' => 'زامبيا', 'ZW' => 'زيمبابوي', 'KR' => 'كوريا الجنوبية', 'PS' => 'فلسطين',
            'TF' => 'الأقاليم الفرنسية الجنوبية', 'VA' => 'الفاتيكان', 'XK' => 'كوسوفو',
        ];
    }
}
