<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Country;
use Illuminate\Database\Seeder;

class WorldCitiesSeeder extends Seeder
{
    public function run(): void
    {
        $countryMap = Country::query()->pluck('id', 'iso2');

        City::withoutEvents(function () use ($countryMap): void {
            foreach ($this->cities() as $iso2 => $cities) {
                $countryId = $countryMap[$iso2] ?? null;
                if (! $countryId) {
                    continue;
                }
                foreach ($cities as $cityName) {
                    City::query()->updateOrCreate(
                        ['country_id' => $countryId, 'name' => $cityName],
                    );
                }
            }
        });
    }

    /**
     * Keys are ISO2 country codes; values are arrays of major city names.
     */
    protected function cities(): array
    {
        return [
            'AF' => ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad'],
            'AL' => ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Fier'],
            'DZ' => ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida'],
            'AD' => ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp'],
            'AO' => ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Kuito'],
            'AG' => ["Saint John's", 'All Saints', 'Liberta'],
            'AR' => ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'Tucumán', 'La Plata', 'Mar del Plata', 'Salta'],
            'AM' => ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat'],
            'AU' => ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Hobart'],
            'AT' => ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'],
            'AZ' => ['Baku', 'Ganja', 'Sumqayit', 'Mingəçevir'],
            'BS' => ['Nassau', 'Freeport', 'West End'],
            'BH' => ['Manama', 'Riffa', 'Muharraq', 'Hamad Town'],
            'BD' => ['Dhaka', 'Chittagong', 'Sylhet', 'Rajshahi', 'Khulna', 'Comilla'],
            'BB' => ['Bridgetown', 'Speightstown', 'Oistins'],
            'BY' => ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno', 'Brest'],
            'BE' => ['Brussels', 'Antwerp', 'Ghent', 'Bruges', 'Liège', 'Namur'],
            'BZ' => ['Belmopan', 'Belize City', 'San Ignacio'],
            'BJ' => ['Cotonou', 'Porto-Novo', 'Parakou', 'Abomey'],
            'BT' => ['Thimphu', 'Phuntsholing', 'Paro'],
            'BO' => ['Sucre', 'La Paz', 'Cochabamba', 'Santa Cruz de la Sierra', 'Oruro', 'Potosí'],
            'BA' => ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar'],
            'BW' => ['Gaborone', 'Francistown', 'Molepolole', 'Kasane'],
            'BR' => ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre'],
            'BN' => ['Bandar Seri Begawan', 'Kuala Belait', 'Seria'],
            'BG' => ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Stara Zagora', 'Ruse'],
            'BF' => ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou'],
            'BI' => ['Bujumbura', 'Gitega', 'Ngozi'],
            'CV' => ['Praia', 'Mindelo', 'Santa Maria'],
            'KH' => ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville'],
            'CM' => ['Yaoundé', 'Douala', 'Bamenda', 'Bafoussam', 'Garoua'],
            'CA' => ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Halifax'],
            'CF' => ['Bangui', 'Bimbo', 'Berbérati'],
            'TD' => ["N'Djamena", 'Moundou', 'Sarh', 'Abéché'],
            'CL' => ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Temuco'],
            'CN' => ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Chongqing', 'Wuhan', 'Tianjin', 'Xi\'an', 'Hangzhou', 'Nanjing', 'Harbin'],
            'CO' => ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Bucaramanga', 'Pereira'],
            'KM' => ['Moroni', 'Mutsamudu', 'Fomboni'],
            'CD' => ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Bukavu'],
            'CG' => ['Brazzaville', 'Pointe-Noire', 'Dolisie'],
            'CR' => ['San José', 'Alajuela', 'Cartago', 'Heredia', 'Liberia'],
            'HR' => ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Dubrovnik'],
            'CU' => ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Santa Clara'],
            'CY' => ['Nicosia', 'Limassol', 'Larnaca', 'Famagusta', 'Paphos'],
            'CZ' => ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc'],
            'CI' => ['Abidjan', 'Bouaké', 'Daloa', 'Yamoussoukro'],
            'DK' => ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg'],
            'DJ' => ['Djibouti City', 'Ali Sabieh', 'Tadjourah'],
            'DM' => ['Roseau', 'Portsmouth'],
            'DO' => ['Santo Domingo', 'Santiago de los Caballeros', 'La Romana', 'San Pedro de Macorís'],
            'EC' => ['Quito', 'Guayaquil', 'Cuenca', 'Ambato', 'Manta'],
            'EG' => ['Cairo', 'Alexandria', 'Giza', 'Shubra El-Kheima', 'Port Said', 'Suez', 'Luxor', 'Aswan'],
            'SV' => ['San Salvador', 'Santa Ana', 'San Miguel', 'Soyapango'],
            'GQ' => ['Malabo', 'Bata', 'Ebebiyín'],
            'ER' => ['Asmara', 'Keren', 'Massawa'],
            'EE' => ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve'],
            'SZ' => ['Mbabane', 'Manzini', 'Lobamba'],
            'ET' => ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar', 'Hawassa', 'Bahir Dar'],
            'FJ' => ['Suva', 'Nadi', 'Lautoka'],
            'FI' => ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku'],
            'FR' => ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'],
            'GA' => ['Libreville', 'Port-Gentil', 'Franceville'],
            'GM' => ['Banjul', 'Serekunda', 'Brikama'],
            'GE' => ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi'],
            'DE' => ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig'],
            'GH' => ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Cape Coast'],
            'GR' => ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Volos'],
            'GD' => ["Saint George's", 'Gouyave', 'Grenville'],
            'GT' => ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango'],
            'GN' => ['Conakry', 'Nzérékoré', 'Kindia', 'Kankan'],
            'GW' => ['Bissau', 'Bafatá', 'Gabú'],
            'GY' => ['Georgetown', 'Linden', 'New Amsterdam'],
            'HT' => ['Port-au-Prince', 'Cap-Haïtien', 'Gonaïves', 'Les Cayes'],
            'HN' => ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba', 'Choloma'],
            'HU' => ['Budapest', 'Debrecen', 'Miskolc', 'Szeged', 'Pécs', 'Győr'],
            'IS' => ['Reykjavik', 'Kópavogur', 'Hafnarfjörður', 'Akureyri'],
            'IN' => ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Ahmedabad', 'Chennai', 'Kolkata', 'Pune', 'Jaipur', 'Surat', 'Lucknow', 'Kanpur'],
            'ID' => ['Jakarta', 'Surabaya', 'Bandung', 'Bekasi', 'Medan', 'Tangerang', 'Depok', 'Semarang', 'Palembang', 'Makassar', 'Bali'],
            'IR' => ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz', 'Ahvaz', 'Qom'],
            'IQ' => ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Sulaymaniyah', 'Kirkuk', 'Najaf'],
            'IE' => ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda'],
            'IL' => ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Beer Sheva'],
            'IT' => ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Venice'],
            'JM' => ['Kingston', 'Montego Bay', 'Spanish Town', 'Portmore'],
            'JP' => ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kyoto', 'Kawasaki', 'Hiroshima', 'Sendai'],
            'JO' => ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Aqaba'],
            'KZ' => ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda', 'Aktobe'],
            'KE' => ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
            'KI' => ['South Tarawa', 'Betio', 'Bikenibeu'],
            'KW' => ['Kuwait City', 'Ahmadi', 'Hawalli', 'Salmiya', 'Jahra'],
            'KG' => ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol'],
            'LA' => ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang'],
            'LV' => ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala'],
            'LB' => ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Zahle'],
            'LS' => ['Maseru', 'Teyateyaneng', 'Mafeteng'],
            'LR' => ['Monrovia', 'Gbarnga', 'Kakata', 'Buchanan'],
            'LY' => ['Tripoli', 'Benghazi', 'Misrata', 'Tarhuna', 'Zawiya'],
            'LI' => ['Vaduz', 'Schaan', 'Balzers'],
            'LT' => ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'],
            'LU' => ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange'],
            'MG' => ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga'],
            'MW' => ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'],
            'MY' => ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Petaling Jaya', 'Johor Bahru', 'Kota Kinabalu', 'Kuching'],
            'MV' => ['Malé', 'Addu City', 'Fuvahmulah'],
            'ML' => ['Bamako', 'Sikasso', 'Mopti', 'Koutiala'],
            'MT' => ['Valletta', 'Birkirkara', 'Qormi', 'Mosta', 'Sliema'],
            'MH' => ['Majuro', 'Ebeye'],
            'MR' => ['Nouakchott', 'Nouadhibou', 'Kiffa'],
            'MU' => ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe'],
            'MX' => ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Ciudad Juárez', 'Zapopan', 'Mérida', 'Cancún'],
            'FM' => ['Palikir', 'Weno', 'Kolonia'],
            'MD' => ['Chișinău', 'Tiraspol', 'Bălți', 'Bender'],
            'MC' => ['Monaco', 'Monte Carlo', 'La Condamine'],
            'MN' => ['Ulaanbaatar', 'Erdenet', 'Darkhan'],
            'ME' => ['Podgorica', 'Nikšić', 'Herceg Novi', 'Bijelo Polje'],
            'MA' => ['Casablanca', 'Rabat', 'Fes', 'Marrakech', 'Tangier', 'Agadir', 'Meknes', 'Oujda'],
            'MZ' => ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio'],
            'MM' => ['Naypyidaw', 'Yangon', 'Mandalay', 'Mawlamyine', 'Bago'],
            'NA' => ['Windhoek', 'Walvis Bay', 'Swakopmund', 'Rundu'],
            'NR' => ['Yaren', 'Baiti', 'Aiwo'],
            'NP' => ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar', 'Birgunj'],
            'NL' => ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen'],
            'NZ' => ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin'],
            'NI' => ['Managua', 'León', 'Masaya', 'Matagalpa', 'Chinandega'],
            'NE' => ['Niamey', 'Zinder', 'Maradi', 'Agadez'],
            'NG' => ['Lagos', 'Kano', 'Ibadan', 'Kaduna', 'Abuja', 'Port Harcourt', 'Benin City', 'Maiduguri', 'Zaria', 'Aba'],
            'KP' => ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo', 'Wonsan'],
            'MK' => ['Skopje', 'Bitola', 'Kumanovo', 'Tetovo'],
            'NO' => ['Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Drammen'],
            'OM' => ['Muscat', 'Salalah', 'Sohar', 'Nizwa', 'Sur'],
            'PK' => ['Karachi', 'Lahore', 'Islamabad', 'Faisalabad', 'Rawalpindi', 'Gujranwala', 'Peshawar', 'Quetta', 'Multan', 'Hyderabad'],
            'PW' => ['Ngerulmud', 'Koror', 'Airai'],
            'PA' => ['Panama City', 'Colón', 'David', 'La Chorrera'],
            'PG' => ['Port Moresby', 'Lae', 'Arawa', 'Mount Hagen'],
            'PY' => ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá'],
            'PE' => ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos', 'Cusco'],
            'PH' => ['Manila', 'Quezon City', 'Davao City', 'Caloocan', 'Cebu City', 'Zamboanga', 'Pasig', 'Antipolo', 'Taguig'],
            'PL' => ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Katowice', 'Lublin'],
            'PT' => ['Lisbon', 'Porto', 'Amadora', 'Braga', 'Setúbal', 'Coimbra', 'Funchal'],
            'QA' => ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor', 'Umm Salal'],
            'RO' => ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov'],
            'RU' => ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Chelyabinsk', 'Omsk', 'Samara', 'Rostov-on-Don', 'Ufa'],
            'RW' => ['Kigali', 'Gitarama', 'Butare', 'Gisenyi'],
            'KN' => ['Basseterre', 'Charlestown'],
            'LC' => ['Castries', 'Gros Islet', 'Vieux Fort'],
            'VC' => ['Kingstown', 'Georgetown', 'Barrouallie'],
            'WS' => ['Apia', 'Vaitele', 'Faleolo'],
            'SM' => ['San Marino', 'Serravalle', 'Borgo Maggiore'],
            'ST' => ['São Tomé', 'Santo António', 'Neves'],
            'SA' => ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Tabuk', 'Abha'],
            'SN' => ['Dakar', 'Touba', 'Thiès', 'Kaolack', 'Saint-Louis'],
            'RS' => ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica'],
            'SC' => ['Victoria', 'Anse Boileau', 'Bel Ombre'],
            'SL' => ['Freetown', 'Kenema', 'Koidu', 'Bo'],
            'SG' => ['Singapore'],
            'SK' => ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Nitra'],
            'SI' => ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper'],
            'SB' => ['Honiara', 'Gizo', 'Auki'],
            'SO' => ['Mogadishu', 'Hargeisa', 'Bosaso', 'Kismayo', 'Berbera'],
            'ZA' => ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Soweto'],
            'SS' => ['Juba', 'Wau', 'Malakal', 'Yei'],
            'ES' => ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao'],
            'LK' => ['Colombo', 'Dehiwala-Mount Lavinia', 'Kandy', 'Jaffna', 'Galle'],
            'SD' => ['Khartoum', 'Omdurman', 'Khartoum North', 'Port Sudan', 'Kassala'],
            'SR' => ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie'],
            'SE' => ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro'],
            'CH' => ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Winterthur', 'Lucerne'],
            'SY' => ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama', 'Deir ez-Zor'],
            'TW' => ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Taoyuan', 'Hsinchu'],
            'TJ' => ['Dushanbe', 'Khujand', 'Kulob', 'Qurghonteppa'],
            'TZ' => ['Dar es Salaam', 'Dodoma', 'Mwanza', 'Arusha', 'Morogoro', 'Zanzibar City'],
            'TH' => ['Bangkok', 'Nonthaburi', 'Pak Kret', 'Hat Yai', 'Chiang Mai', 'Phuket', 'Pattaya'],
            'TL' => ['Dili', 'Baucau', 'Maliana'],
            'TG' => ['Lomé', 'Sokodé', 'Kara', 'Kpalimé'],
            'TO' => ["Nuku'alofa", 'Neiafu', 'Haveluloto'],
            'TT' => ['Port of Spain', 'San Fernando', 'Chaguanas', 'Arima'],
            'TN' => ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Kairouan', 'Bizerte'],
            'TR' => ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana', 'Gaziantep', 'Konya', 'Antalya', 'Kayseri', 'Mersin'],
            'TM' => ['Ashgabat', 'Türkmenabat', 'Daşoguz', 'Mary'],
            'TV' => ['Funafuti', 'Vaiaku', 'Savave'],
            'UG' => ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja'],
            'UA' => ['Kyiv', 'Kharkiv', 'Odessa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv', 'Mykolaiv', 'Mariupol'],
            'AE' => ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah'],
            'GB' => ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Leeds', 'Sheffield', 'Edinburgh', 'Bristol', 'Cardiff', 'Belfast'],
            'US' => ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'San Francisco', 'Charlotte', 'Indianapolis', 'Seattle', 'Denver', 'Nashville', 'Washington D.C.', 'Las Vegas', 'Miami', 'Atlanta', 'Boston'],
            'UY' => ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú'],
            'UZ' => ['Tashkent', 'Namangan', 'Samarkand', 'Andijan', 'Bukhara', 'Ferghana'],
            'VU' => ['Port Vila', 'Luganville', 'Isangel'],
            'VE' => ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana'],
            'VN' => ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hai Phong', 'Can Tho', 'Bien Hoa', 'Hue'],
            'YE' => ["Sana'a", 'Aden', 'Taiz', 'Al Hudaydah', 'Ibb', 'Mukalla'],
            'ZM' => ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola'],
            'ZW' => ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru'],
            'KR' => ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan'],
            'PS' => ['Ramallah', 'Gaza City', 'Hebron', 'Nablus', 'Jenin'],
            'TF' => ['Port-aux-Français'],
            'VA' => ['Vatican City'],
            'XK' => ['Pristina', 'Prizren', 'Peja', 'Gjakova', 'Gjilan'],
        ];
    }
}
