<?php

namespace App\PaymentGateway\Gateways;

use App\PaymentGateway\DTOs\PaymentCharge;
use App\PaymentGateway\DTOs\PaymentResult;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Omnipay\Omnipay;

/**
 * Authorize.Net Gateway
 * Composer:
 *   composer require league/omnipay
 *   composer require academe/omnipay-authorizenetapi
 */
class AuthorizeNetGateway extends AbstractPaymentGateway
{
    private mixed $gateway;

    public function getKey(): string
    {
        return 'authorize_net';
    }

    protected function boot(): void
    {
        $this->requireConfig(['login_id', 'transaction_key']);

        $this->gateway = Omnipay::create('AuthorizeNetApi_Api');
        $this->gateway->setAuthName($this->cfg('login_id'));
        $this->gateway->setTransactionKey($this->cfg('transaction_key'));
        $this->gateway->setTestMode($this->isSandbox());
    }

    public function charge(PaymentCharge $charge): PaymentResult
    {
        // Authorize.Net requires an opaqueDataDescriptor + opaqueDataValue
        // generated by Accept.js on the frontend.
        $descriptor = request()->input('opaqueDataDescriptor')
            ?? session('pgtoken_authorize_net_opaqueDataDescriptor');
        $value = request()->input('opaqueDataValue')
            ?? session('pgtoken_authorize_net_opaqueDataValue');

        session()->forget(['pgtoken_authorize_net_opaqueDataDescriptor', 'pgtoken_authorize_net_opaqueDataValue']);

        if (!$descriptor || !$value) {
            return PaymentResult::failure('Missing Authorize.Net opaque data from Accept.js.');
        }

        try {
            $transactionId = rand(100000000, 999999999);

            $authResponse = $this->gateway->authorize([
                'amount' => $charge->amount,
                'currency' => $charge->currency,
                'transactionId' => $transactionId,
                'opaqueDataDescriptor' => $descriptor,
                'opaqueDataValue' => $value,
            ])->send();

            if (!$authResponse->isSuccessful()) {
                return PaymentResult::failure('Authorization failed: ' . $authResponse->getMessage());
            }

            $captureResponse = $this->gateway->capture([
                'amount' => $charge->amount,
                'currency' => $charge->currency,
                'transactionReference' => $authResponse->getTransactionReference(),
            ])->send();

            if ($captureResponse->isSuccessful()) {
                return PaymentResult::success(
                    $captureResponse->getTransactionReference(),
                    json_encode($captureResponse->getData())
                );
            }

            return PaymentResult::failure('Capture failed: ' . $captureResponse->getMessage());
        } catch (\Throwable $e) {
            return PaymentResult::failure($e->getMessage());
        }
    }

    public function verify(Request $request): PaymentResult
    {
        // Authorize.Net is synchronous; verification happens in charge().
        return PaymentResult::failure('Authorize.Net is synchronous — use charge() directly.');
    }
}
