<?php

namespace App\PaymentGateway\Gateways;

use App\PaymentGateway\DTOs\PaymentCharge;
use App\PaymentGateway\DTOs\PaymentResult;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Session;

/**
 * 2Checkout (Verifone) Gateway
 * No Composer SDK — uses 2Checkout REST APIs (2Pay.js / Inline Checkout).
 * API Docs: https://verifone.cloud/api-catalog
 *
 * NOTE: The old `twocheckout/2checkout-php` library is deprecated.
 * Use the modern 2Pay.js + server-side token authorization below.
 */
class TwoCheckoutGateway extends AbstractPaymentGateway
{
    private const SANDBOX_URL = 'https://api.2checkout.com/rest/6.0/orders/';
    private const PRODUCTION_URL = 'https://api.2checkout.com/rest/6.0/orders/';

    public function getKey(): string
    {
        return '2checkout';
    }

    protected function boot(): void
    {
        $this->requireConfig(['seller_id', 'private_key', 'secret_word']);
    }

    public function charge(PaymentCharge $charge): PaymentResult
    {
        // 2Checkout requires a payment token generated by 2Pay.js on the frontend.
        $token = request()->input('2co_token') ?? session('pgtoken_2checkout_2co_token');

        session()->forget('pgtoken_2checkout_2co_token');

        if (empty($token)) {
            return PaymentResult::failure('2Checkout payment token (2co_token) missing from request.');
        }

        $headers = $this->buildHeaders();

        $payload = [
            'Currency' => $charge->currency,
            'Language' => 'en',
            'CustomerIP' => request()->ip(),
            'Source' => 'WEB',
            'Items' => [
                [
                    'Type' => 'PRODUCT',
                    'Name' => $charge->description,
                    'Quantity' => 1,
                    'Price' => ['Amount' => $charge->amount, 'Type' => 'CUSTOM'],
                    'Tangible' => 'N',
                ]
            ],
            'BillingDetails' => [
                'FirstName' => $charge->name ?? 'Customer',
                'LastName' => '',
                'CountryCode' => 'US',
                'Email' => $charge->email ?? 'noreply@example.com',
                'Address1' => 'N/A',
                'City' => 'N/A',
                'Zip' => '00000',
            ],
            'PaymentDetails' => [
                'Type' => 'EES_TOKEN_PAYMENT',
                'Currency' => $charge->currency,
                'PaymentMethod' => ['EesToken' => $token],
            ],
        ];

        try {
            $response = Http::withHeaders($headers)
                ->post(self::PRODUCTION_URL, $payload);

            $data = $response->json();

            if (!empty($data['RefNo'])) {
                return PaymentResult::success($data['RefNo'], json_encode($data));
            }

            return PaymentResult::failure($data['error_code'] ?? '2Checkout charge failed.');
        } catch (\Throwable $e) {
            return PaymentResult::failure($e->getMessage());
        }
    }

    public function verify(Request $request): PaymentResult
    {
        // 2Checkout uses MD5 hash to verify IPN callbacks.
        $secretWord = $this->cfg('secret_word');
        $sellerId = $this->cfg('seller_id');
        $orderId = $request->input('order_number') ?? $request->input('invoice_id');
        $total = $request->input('invoice_list_amount');
        $hash = $request->input('key');

        $expectedHash = strtoupper(md5($secretWord . $sellerId . $orderId . $total));

        if ($hash !== $expectedHash) {
            return PaymentResult::failure('2Checkout IPN hash verification failed.');
        }

        if ($request->input('message_type') === 'ORDER_CREATED') {
            return PaymentResult::success((string) $orderId);
        }

        return PaymentResult::failure('2Checkout message_type not ORDER_CREATED: ' . $request->input('message_type'));
    }

    public function refund(string $transactionId, float $amount, string $currency, array $context = []): PaymentResult
    {
        $headers = $this->buildHeaders();

        try {
            $response = Http::withHeaders($headers)
                ->post(self::PRODUCTION_URL . $transactionId . '/refund/', [
                    'Reason' => $context['reason'] ?? 'Refund',
                    'Comment' => $context['comment'] ?? 'Refund requested',
                    'RefundType' => 'FULL',
                ]);

            $data = $response->json();

            if ($response->successful()) {
                return PaymentResult::success($transactionId, json_encode($data));
            }

            return PaymentResult::failure($data['error_code'] ?? '2Checkout refund failed.');
        } catch (\Throwable $e) {
            return PaymentResult::failure($e->getMessage());
        }
    }

    public function createWebhook(): array
    {
        return [
            'url' => route('payment.webhook', '2checkout'),
            'events' => ['ORDER_CREATED', 'REFUND_ISSUED'],
        ];
    }

    public function verifyWebhook(Request $request): bool
    {
        $secretWord = $this->cfg('secret_word');
        $sellerId = $this->cfg('seller_id');
        $orderId = $request->input('order_number') ?? $request->input('invoice_id');
        $total = $request->input('invoice_list_amount');
        $hash = $request->input('key');

        if (!$hash) {
            return false;
        }

        $expectedHash = strtoupper(md5($secretWord . $sellerId . $orderId . $total));

        return hash_equals($expectedHash, (string) $hash);
    }

    protected static function meta(): array
    {
        return [
            'currencies' => ['USD', 'EUR', 'GBP'],
            'merchant_countries' => ['US', 'GB', 'DE', 'FR', 'ES', 'IT', 'NL', 'IE', 'SE', 'CA', 'AU', 'JP', 'SG', 'BR', 'MX', 'PL', 'PT', 'BE', 'AT', 'CH'],
            'customer_countries' => ['US', 'GB', 'DE', 'FR', 'ES', 'IT', 'NL', 'IE', 'SE', 'CA', 'AU', 'JP', 'SG', 'BR', 'MX', 'PL', 'PT', 'BE', 'AT', 'CH'],
            'payment_methods' => ['card', 'paypal', 'wallet'],
        ];
    }

    private function buildHeaders(): array
    {
        $date = gmdate('Y-m-d H:i:s');
        $merchantCode = $this->cfg('seller_id');
        $key = $this->cfg('private_key');
        $string = strlen($merchantCode) . $merchantCode . strlen($date) . $date;
        $hash = hash_hmac('md5', $string, $key);

        return [
            'X-Avangate-Authentication' => "code=\"{$merchantCode}\" date=\"{$date}\" hash=\"{$hash}\"",
            'Content-Type' => 'application/json',
            'Accept' => 'application/json',
        ];
    }
}
