<?php

namespace App\Services;

use App\Models\Product;
use App\Models\ProductImageEmbedding;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

/**
 * Image search v1 — expandable to vector DB (pgvector, Pinecone, etc.).
 *
 * Embeddings are generated by the Python microservice (OpenAI vision +
 * text-embedding-3-small, see python-modules/image_search.py) and compared
 * with brute-force cosine similarity here. Swapping the storage/search half
 * for an indexed vector store later does not require changing callers of
 * search()/embedFromUploadedFile() — only this class's internals.
 */
class ImageSearchService
{
    private string $baseUrl;
    private ?string $token;

    public function __construct()
    {
        $this->baseUrl = rtrim((string) config('services.python_modules.url', 'http://127.0.0.1:8008'), '/');
        $this->token = config('services.python_modules.token') ?: null;
    }

    /**
     * Embed an uploaded query image (camera capture or file upload).
     *
     * @return array{embedding: array<float>, dims: int, description: string}
     * @throws \RuntimeException when the service is unreachable or returns an error.
     */
    public function embedFromUploadedFile(UploadedFile $file): array
    {
        $tempPath = $file->getRealPath();

        if (!$tempPath || !is_file($tempPath)) {
            throw new \RuntimeException('The uploaded image could not be read.');
        }

        $mime = $file->getMimeType() ?: 'image/jpeg';
        $dataUrl = 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($tempPath));

        return $this->callEndpoint('/image-search', ['image_path' => $dataUrl]);
    }

    /**
     * Embed a product's primary image, gallery images, and any per-variant
     * images, upserting each into the embeddings table so image search can
     * match on any photo of the product, not just the primary one.
     */
    public function backfillForProduct(Product $product): void
    {
        $product->loadMissing(['files', 'variants.files']);

        $this->embedOne($product->id, null, 'primary', $product->primary_image_url);

        $galleryFiles = $product->files->where('key', 'gallery');
        foreach ($galleryFiles as $file) {
            $this->embedOne($product->id, null, 'gallery-' . $file->id, $file->full_path);
        }

        $variantIds = [];
        foreach ($product->variants as $variant) {
            $variantIds[] = $variant->id;
            $variantImage = $variant->files->firstWhere('key', 'variant_thumb');
            $this->embedOne($product->id, $variant->id, 'variant', $variantImage?->full_path);
        }

        // Drop embeddings for gallery images / variants that no longer exist,
        // so deleted photos can't linger as false matches.
        $keepGallerySources = $galleryFiles->map(fn($f) => 'gallery-' . $f->id)->all();

        ProductImageEmbedding::query()
            ->where('product_id', $product->id)
            ->whereNull('variant_id')
            ->where('source', 'like', 'gallery-%')
            ->whereNotIn('source', $keepGallerySources ?: [''])
            ->delete();

        ProductImageEmbedding::query()
            ->where('product_id', $product->id)
            ->where('source', 'variant')
            ->whereNotIn('variant_id', $variantIds ?: [0])
            ->delete();
    }

    private function embedOne(int $productId, ?int $variantId, string $source, ?string $imageUrl): void
    {
        if (!$imageUrl) {
            return;
        }

        try {
            $result = $this->callEndpoint('/image-search', ['image_path' => $imageUrl]);
        } catch (\RuntimeException $e) {
            Log::warning('[ImageSearchService] Skipped embedding for product image.', [
                'product_id' => $productId,
                'variant_id' => $variantId,
                'source' => $source,
                'message' => $e->getMessage(),
            ]);
            return;
        }

        ProductImageEmbedding::updateOrCreate(
            ['product_id' => $productId, 'variant_id' => $variantId, 'source' => $source],
            ['embedding' => $result['embedding'], 'dims' => $result['dims']],
        );
    }

    /**
     * Rank candidate product IDs by cosine similarity to a query embedding.
     *
     * @param array<float> $queryEmbedding
     * @param array<int> $candidateProductIds
     * @return array<int> product IDs sorted by descending similarity
     */
    public function search(array $queryEmbedding, array $candidateProductIds, int $limit = 24): array
    {
        if (empty($candidateProductIds)) {
            return [];
        }

        $rows = ProductImageEmbedding::query()
            ->whereIn('product_id', $candidateProductIds)
            ->get(['product_id', 'embedding']);

        $scored = [];
        foreach ($rows as $row) {
            $score = self::cosineSimilarity($queryEmbedding, $row->embedding ?? []);
            // Keep the best-scoring row per product (e.g. multiple sources later).
            if (!isset($scored[$row->product_id]) || $score > $scored[$row->product_id]) {
                $scored[$row->product_id] = $score;
            }
        }

        arsort($scored);

        return array_slice(array_keys($scored), 0, $limit);
    }

    private static function cosineSimilarity(array $a, array $b): float
    {
        if (empty($a) || empty($b) || count($a) !== count($b)) {
            return -1.0;
        }

        $dot = 0.0;
        $normA = 0.0;
        $normB = 0.0;

        foreach ($a as $i => $valueA) {
            $valueB = $b[$i];
            $dot += $valueA * $valueB;
            $normA += $valueA ** 2;
            $normB += $valueB ** 2;
        }

        if ($normA <= 0.0 || $normB <= 0.0) {
            return -1.0;
        }

        return $dot / (sqrt($normA) * sqrt($normB));
    }

    /**
     * @throws \RuntimeException when the service is unreachable or returns an error.
     */
    private function callEndpoint(string $path, array $payload): array
    {
        try {
            $request = Http::timeout(60)->acceptJson();

            if ($this->token) {
                $request = $request->withHeaders(['X-Service-Token' => $this->token]);
            }

            $response = $request->post($this->baseUrl . $path, $payload);

            if ($response->failed()) {
                $detail = $response->json('detail') ?? $response->body();

                Log::error('[ImageSearchService] HTTP error.', [
                    'status' => $response->status(),
                    'body' => $response->body(),
                ]);

                throw new \RuntimeException($detail ?: 'The AI image search service returned an error.');
            }

            return $response->json();
        } catch (\Illuminate\Http\Client\ConnectionException $e) {
            Log::error('[ImageSearchService] Connection exception.', ['message' => $e->getMessage()]);
            throw new \RuntimeException('The AI image search service is unavailable. Make sure the Python service is running.', previous: $e);
        }
    }
}
