import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/elora.css',
                'resources/css/elora-v2.css',
                'resources/css/elora-v3.css',
                'resources/css/elora-v4.css',
                'resources/css/elora-v5.css',
                'resources/css/elora-v6.css',
                'resources/css/elora/category.css',
                'resources/css/elora/footer.css',
                'resources/css/elora/footer-v2.css',
                'resources/css/elora/footer-v3.css',
                'resources/css/elora/footer-v4.css',
                'resources/css/elora/footer-v5.css',
                'resources/css/elora/footer-v6.css',
                'resources/css/elora/header.css',
                'resources/css/elora/header-v2.css',
                'resources/css/elora/header-v3.css',
                'resources/css/elora/header-v4.css',
                'resources/css/elora/header-v5.css',
                'resources/css/elora/header-v6.css',
                'resources/css/elora/home.css',
                'resources/css/elora/home-v2.css',
                'resources/css/elora/home-v3.css',
                'resources/css/elora/home-v4.css',
                'resources/css/elora/home-v5.css',
                'resources/css/elora/home-v6.css',
                'resources/css/ecommet.css',
                'resources/css/souqify.css',
                'resources/js/app.js',
                'resources/js/storefront-cart.js',
                'resources/js/image-search.js',
                'resources/js/elora.js',
                'resources/js/elora/cart.js',
                'resources/js/elora/category.js',
                'resources/js/elora/footer.js',
                'resources/js/elora/footer-v2.js',
                'resources/js/elora/footer-v3.js',
                'resources/js/elora/footer-v4.js',
                'resources/js/elora/footer-v5.js',
                'resources/js/elora/footer-v6.js',
                'resources/js/elora/header.js',
                'resources/js/elora/header-v2.js',
                'resources/js/elora/header-v3.js',
                'resources/js/elora/header-v4.js',
                'resources/js/elora/header-v5.js',
                'resources/js/elora/header-v6.js',
                'resources/js/elora/home.js',
                'resources/js/elora/product.js',
                'resources/js/ecommet.js',
                'resources/js/ecommet/cart.js',
                'resources/js/ecommet/home.js',
                'resources/js/ecommet/product.js',
                'resources/js/souqify.js',
                'resources/js/website.js',
                'resources/css/website.css',
                'resources/js/elora-v2-interactions.js',
                'resources/js/elora-v2-carousels.js',
                'resources/js/elora-v3-interactions.js',
                'resources/js/elora-v3-carousels.js',
                'resources/js/elora-v4-interactions.js',
                'resources/js/elora-v4-carousels.js',
                'resources/js/elora-v5-interactions.js',
                'resources/js/elora-v5-carousels.js',
                'resources/js/elora-v6-interactions.js',
                'resources/js/elora-v6-carousels.js'
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
    server: {
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});
