<?php

declare(strict_types=1);

namespace App\Http\Controllers\Tenant;

use App\Models\Tenant\AdminUser as TenantAdminUser;
use App\Models\Tenant\AdminRole as TenantAdminRole;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;

/**
 * Accepts a central-admin impersonation token, logs the caller into the tenant
 * admin panel, then redirects to the tenant dashboard.
 *
 * Called from:  GET {tenant-domain}/admin/impersonate/{token}
 *
 * The matching token was generated by
 * App\Http\Controllers\Admin\TenantImpersonateController::generate().
 *
 * Security:
 *   - Token must exist in cache (max 90 s old, single-use).
 *   - Token is deleted immediately after validation.
 *   - Logs in as the tenant's primary super-admin (store owner role).
 */
class TenantImpersonateController
{
    public function accept(Request $request, string $token): RedirectResponse
    {
        $cacheKey = "tenant_impersonate:{$token}";

        // The token was stored in the CENTRAL cache context.
        // By the time this controller runs tenancy is already initialised, so
        // CacheTenancyBootstrapper has scoped the default cache store with tags.
        // File/database cache drivers do not support tagging and would throw
        // "This cache store does not support tagging."
        // We therefore read and delete the token from the central context.
        $payload = tenancy()->central(fn() => Cache::get($cacheKey));

        if (!$payload) {
            abort(403, 'This impersonation link has expired or is invalid.');
        }

        // Consume the token immediately (single-use).
        tenancy()->central(fn() => Cache::forget($cacheKey));

        // Validate the token belongs to THIS tenant (tenancy is already
        // initialised by the route middleware at this point).
        $currentTenantId = tenancy()->tenant?->id;

        if (($payload['tenant_id'] ?? null) !== $currentTenantId) {
            abort(403, 'Token tenant mismatch.');
        }

        // Find the primary store-owner account in this tenant's DB.
        $owner = TenantAdminUser::query()
            ->whereHas('role', fn($q) => $q->where('name', TenantAdminRole::STORE_OWNER))
            ->first();

        if (!$owner) {
            // Fall back to any active admin in the tenant DB.
            $owner = TenantAdminUser::query()->first();
        }

        if (!$owner) {
            abort(404, 'No admin user found in this tenant.');
        }

        // Log in as the tenant admin.
        Auth::guard('tenant')->login($owner);

        $request->session()->regenerate();

        return redirect()->route('tenant.dashboard');
    }
}
