"""FastAPI entry-point that exposes the AI modules as HTTP endpoints so the
Laravel app (or any other HTTP client) can call them without having to embed
Python.

Endpoints
─────────
  POST /price
      JSON: {"product_name": "iPhone 15 Pro", "limit": 8}
      or:   {"image_path": "/var/www/multi-vendor/storage/app/public/products/x.jpg", "limit": 8}
      or both (image + product_name as a hint for the vision lookup).
      "image_path" accepts an absolute local filesystem path or a public image URL.
      Returns an aggregated price report with min/median/avg/max + per-source hits.

  POST /social-post
      JSON: {"title": "...", "description": "...", "platform": "instagram"|...|"all",
             "include_image": true}
      Returns captions per platform plus a base64-encoded generated image.

  POST /generate-logo
      JSON: {"store_name": "...", "tagline": "...", "category": "fashion",
             "style": "modern", "colors": "blue and gold"}
      Returns a base64-encoded PNG logo generated by DALL·E 3.

  POST /image-search
      JSON: {"image_path": "/var/www/multi-vendor/storage/app/public/products/x.jpg"}
      "image_path" accepts an absolute local filesystem path or a public image URL.
      Returns an embedding vector for the image (Image search v1 — see image_search.py;
      expandable to vector DB (pgvector, Pinecone, etc.)).

  GET /health
      Liveness probe.
"""

from __future__ import annotations

import logging
import os
from dataclasses import asdict
from typing import Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from price_finder import find_average_price
from social_post_generator import SUPPORTED_PLATFORMS, generate_posts
from logo_generator import (
    SUPPORTED_STYLES,
    SUPPORTED_CATEGORIES,
    generate_logo,
)
from image_search import embed_image

load_dotenv()

logging.basicConfig(level=os.getenv("LOG_LEVEL", "INFO").upper())
logger = logging.getLogger("python-modules")

app = FastAPI(
    title="Multi-Vendor AI Modules",
    version="1.0.0",
    description="Price discovery + social post generation for the Laravel multi-vendor platform.",
)

# Optional shared secret so only the Laravel backend can call these endpoints.
# Clients must send the matching header when SERVICE_TOKEN is set.
SERVICE_TOKEN = os.getenv("SERVICE_TOKEN", "").strip()

# Configurable CORS — safe defaults (same-origin / server-to-server only).
_allowed = [o.strip() for o in os.getenv("ALLOWED_ORIGINS", "").split(",") if o.strip()]
app.add_middleware(
    CORSMiddleware,
    allow_origins=_allowed or ["*"] if os.getenv("ALLOW_ANY_ORIGIN") == "1" else _allowed,
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)


# ── Schemas ──────────────────────────────────────────────────────────────────

class PriceRequest(BaseModel):
    product_name: str = Field("", max_length=200)
    image_path: Optional[str] = Field(None, max_length=2000, description="Absolute local file path or public URL of the product/variant image.")
    limit: int = Field(8, ge=1, le=20)


class SocialPostRequest(BaseModel):
    title: str = Field(..., min_length=1, max_length=200)
    description: str = Field(..., min_length=1, max_length=2000)
    language_code: Optional[str] = Field(None, min_length=2, max_length=16)
    language_name: Optional[str] = Field(None, min_length=1, max_length=100)
    platform: str = Field("all", description=f"One of: {', '.join(SUPPORTED_PLATFORMS)} or 'all'")
    include_image: bool = True
    text_model: Optional[str] = None
    image_model: Optional[str] = None


class ImageSearchRequest(BaseModel):
    image_path: str = Field(..., min_length=1, max_length=15_000_000, description="Absolute local file path, public URL, or base64 data URL of the query image.")


class LogoGenerateRequest(BaseModel):
    store_name: str = Field(..., min_length=1, max_length=100)
    tagline: Optional[str] = Field(None, max_length=200)
    category: str = Field("general", description=f"One of: {', '.join(SUPPORTED_CATEGORIES)}")
    style: str = Field("modern", description=f"One of: {', '.join(SUPPORTED_STYLES)}")
    colors: Optional[str] = Field(None, max_length=200)
    model: Optional[str] = None


# ── Auth helper ──────────────────────────────────────────────────────────────

from fastapi import Header


def _auth(x_service_token: Optional[str] = Header(default=None)) -> None:
    if not SERVICE_TOKEN:
        return  # auth disabled
    if x_service_token != SERVICE_TOKEN:
        raise HTTPException(status_code=401, detail="Invalid or missing X-Service-Token header.")


# ── Routes ───────────────────────────────────────────────────────────────────

@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


@app.post("/price")
async def price(req: PriceRequest, x_service_token: Optional[str] = Header(default=None)) -> dict:
    _auth(x_service_token)
    try:
        report = await find_average_price(req.product_name, limit=req.limit, image_path=req.image_path)
        return asdict(report)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        logger.exception("price endpoint failed")
        raise HTTPException(status_code=500, detail=f"Price lookup failed: {exc}")


@app.post("/social-post")
def social_post(req: SocialPostRequest, x_service_token: Optional[str] = Header(default=None)) -> dict:
    _auth(x_service_token)
    try:
        bundle = generate_posts(
            title=req.title,
            description=req.description,
            language_code=req.language_code,
            language_name=req.language_name,
            platform=req.platform,
            include_image=req.include_image,
            text_model=req.text_model,
            image_model=req.image_model,
        )
        return asdict(bundle)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    except RuntimeError as exc:
        # Missing API key etc. — surface clearly.
        raise HTTPException(status_code=503, detail=str(exc))
    except Exception as exc:
        logger.exception("social-post endpoint failed")
        raise HTTPException(status_code=500, detail=f"Generation failed: {exc}")


@app.post("/image-search")
def image_search(req: ImageSearchRequest, x_service_token: Optional[str] = Header(default=None)) -> dict:
    _auth(x_service_token)
    try:
        result = embed_image(req.image_path)
        return {
            "embedding": result.embedding,
            "dims": result.dims,
            "description": result.description,
        }
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc))
    except Exception as exc:
        logger.exception("image-search endpoint failed")
        raise HTTPException(status_code=500, detail=f"Image search failed: {exc}")


@app.post("/generate-logo")
def logo_generate(
    req: LogoGenerateRequest,
    x_service_token: Optional[str] = Header(default=None),
) -> dict:
    _auth(x_service_token)
    try:
        result = generate_logo(
            store_name=req.store_name,
            tagline=req.tagline,
            category=req.category,
            style=req.style,
            colors=req.colors,
            model=req.model,
        )
        return {
            "image_b64": result.image_b64,
            "prompt_used": result.prompt_used,
            "revised_prompt": result.revised_prompt,
            "model": result.model,
        }
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc))
    except Exception as exc:
        logger.exception("generate-logo endpoint failed")
        raise HTTPException(status_code=500, detail=f"Logo generation failed: {exc}")
